### ISSUE TITLE
[bug] Error on initial setup

### ISSUE THREAD

**Issue by cchurchw** [bactopia/bactopia#106]
Had error on initial running of bactopia.

OS : NAME="CentOS Linux" VERSION="7 (Core)" ID="centos"

```
2020-05-19 17:12:14:root:INFO - Found /rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/share/bactopia-1.3.1/conda/call_variants.yml (5 or 12), begin build to /rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/share/bactopia-1.3.1/conda/envs/call_variants-1.3.1
Traceback (most recent call last):
  File "/rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/bin/bactopia-build.py", line 119, in <module>
    execute(f'conda env create -f {env_file} --prefix {prefix} {force}')
  File "/rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/bin/bactopia-build.py", line 51, in execute
    command.start()
  File "/rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/lib/python3.6/site-packages/executor/__init__.py", line 1441, in start
    self.start_once(**kw)
  File "/rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/lib/python3.6/site-packages/executor/__init__.py", line 1508, in start_once
    self.wait(check=check)
  File "/rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/lib/python3.6/site-packages/executor/__init__.py", line 1551, in wait
    self.check_errors(check=check)
  File "/rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/lib/python3.6/site-packages/executor/__init__.py", line 1673, in check_errors
    raise self.error_type(self)
executor.ExternalCommandFailed: External command failed with exit code 1!

Command:
bash -c 'conda env create -f /rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/share/bactopia-1.3.1/conda/call_variants.yml --prefix /rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/share/bactopia-1.3.1/conda/envs/call_variants-1.3.1 --force'

Standard output:
EnvironmentSectionNotValid: The following section on '/rds/general/user/cchurchw/home/anaconda3/envs/bactopia2/share/bactopia-1.3.1/conda/call_variants.yml' is invalid and will be ignored:
 - version

Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Standard error:
ResolvePackageNotFound: 
  - openjdk==8.0.192=h516909a_1004
```

Changed line 66 of call_variants.yml to " - openjdk=8.0.192=h14c3975_1003" to roll back version openjdk. Looks as others have had same [issue](https://github.com/conda-forge/r-rjava-feedstock/issues/13) 

Program looks good and looking forward to trying it!

**Comment by rpetit3** [comment]
Hi @cchurchw 

Thanks for the info! I haven't been able to test on Cent OS. I'm going to test the roll back on Ubuntu and likely get it put into the next version of Bactopia.

Thanks again, and please don't hesitate to reach out if you uncover anything else.

Cheers,
Robert

**Comment by rpetit3** [comment]
Hi @cchurchw 

Thanks again for the heads up about this. I'm implemented your fall back and it will be reflected in the next version update.

Going to close for now, please feel free to reopen if the issue pops back up.

Cheers,
Robert
