### ISSUE TITLE
[bug] bactopia datasets - File of accessions not working with latest changes

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#112]
**Description**
The latest changes to `bactopia datasets` broke the file based accessions.

**Steps to Reproduce**
Provide a file with accessions
```
timothyread$ bactopia datasets datasets --ariba "vfdb_core" --species "Staphylococcus aureus" --accessions complete_genome_projects --cpus 4
2020-08-07 18:01:04:root:INFO - Staphylococcus aureus verified in ENA Taxonomy database
2020-08-07 18:01:04:root:INFO - Setting up Ariba datasets
2020-08-07 18:01:04:root:INFO - Setting up vfdb_core Ariba dataset
2020-08-07 18:05:45:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2020-08-07 21:24:13:root:INFO - Setting up pre-computed PLSDB (plasmids) datasets
2020-08-08 00:27:29:root:INFO - Setting up MLST datasets
2020-08-08 00:27:29:root:INFO - Setting up default MLST schema for Staphylococcus aureus
2020-08-08 00:27:29:root:INFO - Creating Ariba MLST dataset
2020-08-08 00:28:25:root:INFO - Creating BLAST MLST dataset
2020-08-08 00:28:26:root:INFO - Setting up custom Prokka proteins
2020-08-08 00:28:26:root:INFO - Setting up custom Prokka proteins for Staphylococcus aureus
2020-08-08 00:28:26:root:INFO - Downloading completed genomes
Traceback (most recent call last):
 File "/Users/timothyread/miniconda3/envs/bactopia/bin/bactopia-datasets.py", line 1026, in <module>
  force=(args.force or args.force_prokka)
 File "/Users/timothyread/miniconda3/envs/bactopia/bin/bactopia-datasets.py", line 467, in setup_prokka
  accessions_dl = accessions
UnboundLocalError: local variable 'accessions' referenced before assignment
```

**Additional Information**
tagging @plasmid02

**Comment by rpetit3** [comment]
fixed: https://github.com/bactopia/bactopia/commit/1ba6ac56587b4ecc6ebf9ff7923c73b177b6a7c7
