### ISSUE TITLE
datasets card download issue

### ISSUE THREAD

**Issue by plasmid02** [bactopia/bactopia#113]
**Description**
bactopia datasets fails to download latest version of card and ends with error

**Steps to Reproduce**
```
bactopia datasets datasets --ariba "vfdb_core, card" --species "Staphylococcus aureus" --accessions complete_genome_projects --cpus 4
```

**Expected Behavior**
download card and carry on
**Execution Environment**

- Bactopia Version: [output from `bactopia version`]
- bactopia 1.4.2
- OS: Mac
- Environment: conda

**Additional Information**
```
2020-08-11 19:44:02:root:INFO - Staphylococcus aureus verified in ENA Taxonomy database
2020-08-11 19:44:02:root:INFO - Setting up Ariba datasets
2020-08-11 19:44:02:root:INFO - Setting up vfdb_core Ariba dataset
2020-08-11 19:48:25:root:INFO - Setting up card Ariba dataset
Traceback (most recent call last):
  File "/Users/timothyread/miniconda3/envs/bactopia/bin/bactopia-datasets.py", line 1024, in <module>
    force=(args.force or args.force_ariba)
  File "/Users/timothyread/miniconda3/envs/bactopia/bin/bactopia-datasets.py", line 286, in setup_ariba
    directory=ariba_dir
  File "/Users/timothyread/miniconda3/envs/bactopia/bin/bactopia-datasets.py", line 819, in execute
    command.start()
  File "/Users/timothyread/miniconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1441, in start
    self.start_once(**kw)
  File "/Users/timothyread/miniconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1508, in start_once
    self.wait(check=check)
  File "/Users/timothyread/miniconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1551, in wait
    self.check_errors(check=check)
  File "/Users/timothyread/miniconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1673, in check_errors
    raise self.error_type(self)
executor.ExternalCommandFailed: External command failed with exit code 1!

Command:
bash -c 'ariba getref card card'

Standard output:
Getting available CARD versions
Downloading "https://card.mcmaster.ca/download" and saving as "download.html" ... done
Found versions:
1.0.0	https://card.mcmaster.ca/download/0/broadstreet-v1.0.0.tar.bz2
1.0.1	https://card.mcmaster.ca/download/0/broadstreet-v1.0.1.tar.bz2
1.0.2	https://card.mcmaster.ca/download/0/broadstreet-v1.0.2.tar.bz2
1.0.3	https://card.mcmaster.ca/download/0/broadstreet-v1.0.3.tar.bz2
1.0.4	https://card.mcmaster.ca/download/0/broadstreet-v1.0.4.tar.bz2
1.0.5	https://card.mcmaster.ca/download/0/broadstreet-v1.0.5.tar.bz2
1.0.6	https://card.mcmaster.ca/download/0/broadstreet-v1.0.6.tar.bz2
1.0.7	https://card.mcmaster.ca/download/0/broadstreet-v1.0.7.tar.bz2
1.0.8	https://card.mcmaster.ca/download/0/broadstreet-v1.0.8.tar.bz2
1.0.9	https://card.mcmaster.ca/download/0/broadstreet-v1.0.9.tar.bz2
1.1.0	https://card.mcmaster.ca/download/0/broadstreet-v1.1.0.tar.bz2
1.1.1	https://card.mcmaster.ca/download/0/broadstreet-v1.1.1.tar.bz2
1.1.2	https://card.mcmaster.ca/download/0/broadstreet-v1.1.2.tar.bz2
1.1.3	https://card.mcmaster.ca/download/0/broadstreet-v1.1.3.tar.bz2
1.1.4	https://card.mcmaster.ca/download/0/broadstreet-v1.1.4.tar.bz2
1.1.5	https://card.mcmaster.ca/download/0/broadstreet-v1.1.5.tar.bz2
1.1.6	https://card.mcmaster.ca/download/0/broadstreet-v1.1.6.tar.bz2
1.1.7	https://card.mcmaster.ca/download/0/broadstreet-v1.1.7.tar.bz2
1.1.8	https://card.mcmaster.ca/download/0/broadstreet-v1.1.8.tar.bz2
1.1.9	https://card.mcmaster.ca/download/0/broadstreet-v1.1.9.tar.bz2
1.2.0	https://card.mcmaster.ca/download/0/broadstreet-v1.2.0.tar.bz2
1.2.1	https://card.mcmaster.ca/download/0/broadstreet-v1.2.1.tar.bz2
2.0.0	https://card.mcmaster.ca/download/0/broadstreet-v2.0.0.tar.gz
2.0.1	https://card.mcmaster.ca/download/0/broadstreet-v2.0.1.tar.gz
2.0.2	https://card.mcmaster.ca/download/0/broadstreet-v2.0.2.tar.gz
2.0.3	https://card.mcmaster.ca/download/0/broadstreet-v2.0.3.tar.gz
3.0.0	https://card.mcmaster.ca/download/0/broadstreet-v3.0.0.tar.gz
3.0.1	https://card.mcmaster.ca/download/0/broadstreet-v3.0.1.tar.gz
3.0.2	https://card.mcmaster.ca/download/0/broadstreet-v3.0.2.tar.gz
3.0.3	https://card.mcmaster.ca/download/0/broadstreet-v3.0.3.tar.gz
3.0.4	https://card.mcmaster.ca/download/0/broadstreet-v3.0.4.tar.gz
3.0.5	https://card.mcmaster.ca/download/0/broadstreet-v3.0.5.tar.gz
3.0.6	https://card.mcmaster.ca/download/0/broadstreet-v3.0.6.tar.gz
3.0.7	https://card.mcmaster.ca/download/0/broadstreet-v3.0.7.tar.gz
3.0.8	https://card.mcmaster.ca/download/0/broadstreet-v3.0.8.tar.bz2
3.0.9	https://card.mcmaster.ca/download/0/broadstreet-v3.0.9.tar.bz2
3.1.0	https://card.mcmaster.ca/download/0/broadstreet-v3.1.0.tar.bz2
5.1.0	https://card.mcmaster.ca/download/1/software-v5.1.1.tar.bz2">DOWNLOAD</a></td></tr><div id="other-software" class="more collapse"><tr class="more-software collapse"><td>RGI Software</td><td class="hidden-xs">RGI version 5.1.0 - added beta version for K-mer taxonomic classifiers (rgi kmer_build and rgi kmer_query), updated the code to accept a broader range of nucleotide redundancy codes, and set biopython to version 1.72 due to bug on biopython version 1.74</td><td class="hidden-xs">5.1.0</td><td class="hidden-xs">TAR</td><td class="hidden-xs">2019-08-22 09:43:12.5152</td><td><a href="/download/1/software-v5.1.0.tar.gz
Getting version 5.1.0
Working in temporary directory /Users/timothyread/staphopia_dataset/datasets/ariba/card.download
Downloading data from card: https://card.mcmaster.ca/download/1/software-v5.1.1.tar.bz2">DOWNLOAD</a></td></tr><div id="other-software" class="more collapse"><tr class="more-software collapse"><td>RGI Software</td><td class="hidden-xs">RGI version 5.1.0 - added beta version for K-mer taxonomic classifiers (rgi kmer_build and rgi kmer_query), updated the code to accept a broader range of nucleotide redundancy codes, and set biopython to version 1.72 due to bug on biopython version 1.74</td><td class="hidden-xs">5.1.0</td><td class="hidden-xs">TAR</td><td class="hidden-xs">2019-08-22 09:43:12.5152</td><td><a href="/download/1/software-v5.1.0.tar.gz
syscall: wget -O card.tar.bz2 https://card.mcmaster.ca/download/1/software-v5.1.1.tar.bz2">DOWNLOAD</a></td></tr><div id="other-software" class="more collapse"><tr class="more-software collapse"><td>RGI Software</td><td class="hidden-xs">RGI version 5.1.0 - added beta version for K-mer taxonomic classifiers (rgi kmer_build and rgi kmer_query), updated the code to accept a broader range of nucleotide redundancy codes, and set biopython to version 1.72 due to bug on biopython version 1.74</td><td class="hidden-xs">5.1.0</td><td class="hidden-xs">TAR</td><td class="hidden-xs">2019-08-22 09:43:12.5152</td><td><a href="/download/1/software-v5.1.0.tar.gz
The following command failed with exit code 4
wget -O card.tar.bz2 https://card.mcmaster.ca/download/1/software-v5.1.1.tar.bz2">DOWNLOAD</a></td></tr><div id="other-software" class="more collapse"><tr class="more-software collapse"><td>RGI Software</td><td class="hidden-xs">RGI version 5.1.0 - added beta version for K-mer taxonomic classifiers (rgi kmer_build and rgi kmer_query), updated the code to accept a broader range of nucleotide redundancy codes, and set biopython to version 1.72 due to bug on biopython version 1.74</td><td class="hidden-xs">5.1.0</td><td class="hidden-xs">TAR</td><td class="hidden-xs">2019-08-22 09:43:12.5152</td><td><a href="/download/1/software-v5.1.0.tar.gz

The output was:

--2020-08-11 19:48:30--  https://card.mcmaster.ca/download/1/software-v5.1.1.tar.bz2%3EDOWNLOAD%3C/a%3E%3C/td%3E%3C/tr%3E%3Cdiv%20id=other-software%20class=more
Resolving card.mcmaster.ca (card.mcmaster.ca)... 130.113.77.126
Connecting to card.mcmaster.ca (card.mcmaster.ca)|130.113.77.126|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-11 19:48:30 ERROR 404: Not Found.

--2020-08-11 19:48:30--  http://collapse%3E%3Ctr%20class=more-software/
Resolving collapse><tr class=more-software (collapse><tr class=more-software)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘collapse><tr class=more-software’
--2020-08-11 19:48:30--  http://collapse%3E%3Ctd%3Ergi%20software%3C/td%3E%3Ctd%20class=hidden-xs%3ERGI%20version%205.1.0%20-%20added%20beta%20version%20for%20K-mer%20taxonomic%20classifiers%20(rgi%20kmer_build%C2%A0and%C2%A0rgi%20kmer_query),%20updated%20the%20code%20to%20accept%20a%20broader%20range%20of%20nucleotide%20redundancy%20codes,%20and%20set%20biopython%20to%20version%201.72%20due%20to%20bug%20on%20biopython%20version%201.74%3C/td%3E%3Ctd%20class=hidden-xs%3E5.1.0%3C/td%3E%3Ctd%20class=hidden-xs%3ETAR%3C/td%3E%3Ctd%20class=hidden-xs%3E2019-08-22%2009:43:12.5152%3C/td%3E%3Ctd%3E%3Ca%20href=/download/1/software-v5.1.0.tar.gz
Resolving collapse><td>rgi software< (collapse><td>rgi software<)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘collapse><td>rgi software<’

Standard error:
Getting available CARD versions
Downloading "https://card.mcmaster.ca/download" and saving as "download.html" ... done
Found versions:
1.0.0	https://card.mcmaster.ca/download/0/broadstreet-v1.0.0.tar.bz2
1.0.1	https://card.mcmaster.ca/download/0/broadstreet-v1.0.1.tar.bz2
1.0.2	https://card.mcmaster.ca/download/0/broadstreet-v1.0.2.tar.bz2
1.0.3	https://card.mcmaster.ca/download/0/broadstreet-v1.0.3.tar.bz2
1.0.4	https://card.mcmaster.ca/download/0/broadstreet-v1.0.4.tar.bz2
1.0.5	https://card.mcmaster.ca/download/0/broadstreet-v1.0.5.tar.bz2
1.0.6	https://card.mcmaster.ca/download/0/broadstreet-v1.0.6.tar.bz2
1.0.7	https://card.mcmaster.ca/download/0/broadstreet-v1.0.7.tar.bz2
1.0.8	https://card.mcmaster.ca/download/0/broadstreet-v1.0.8.tar.bz2
1.0.9	https://card.mcmaster.ca/download/0/broadstreet-v1.0.9.tar.bz2
1.1.0	https://card.mcmaster.ca/download/0/broadstreet-v1.1.0.tar.bz2
1.1.1	https://card.mcmaster.ca/download/0/broadstreet-v1.1.1.tar.bz2
1.1.2	https://card.mcmaster.ca/download/0/broadstreet-v1.1.2.tar.bz2
1.1.3	https://card.mcmaster.ca/download/0/broadstreet-v1.1.3.tar.bz2
1.1.4	https://card.mcmaster.ca/download/0/broadstreet-v1.1.4.tar.bz2
1.1.5	https://card.mcmaster.ca/download/0/broadstreet-v1.1.5.tar.bz2
1.1.6	https://card.mcmaster.ca/download/0/broadstreet-v1.1.6.tar.bz2
1.1.7	https://card.mcmaster.ca/download/0/broadstreet-v1.1.7.tar.bz2
1.1.8	https://card.mcmaster.ca/download/0/broadstreet-v1.1.8.tar.bz2
1.1.9	https://card.mcmaster.ca/download/0/broadstreet-v1.1.9.tar.bz2
1.2.0	https://card.mcmaster.ca/download/0/broadstreet-v1.2.0.tar.bz2
1.2.1	https://card.mcmaster.ca/download/0/broadstreet-v1.2.1.tar.bz2
2.0.0	https://card.mcmaster.ca/download/0/broadstreet-v2.0.0.tar.gz
2.0.1	https://card.mcmaster.ca/download/0/broadstreet-v2.0.1.tar.gz
2.0.2	https://card.mcmaster.ca/download/0/broadstreet-v2.0.2.tar.gz
2.0.3	https://card.mcmaster.ca/download/0/broadstreet-v2.0.3.tar.gz
3.0.0	https://card.mcmaster.ca/download/0/broadstreet-v3.0.0.tar.gz
3.0.1	https://card.mcmaster.ca/download/0/broadstreet-v3.0.1.tar.gz
3.0.2	https://card.mcmaster.ca/download/0/broadstreet-v3.0.2.tar.gz
3.0.3	https://card.mcmaster.ca/download/0/broadstreet-v3.0.3.tar.gz
3.0.4	https://card.mcmaster.ca/download/0/broadstreet-v3.0.4.tar.gz
3.0.5	https://card.mcmaster.ca/download/0/broadstreet-v3.0.5.tar.gz
3.0.6	https://card.mcmaster.ca/download/0/broadstreet-v3.0.6.tar.gz
3.0.7	https://card.mcmaster.ca/download/0/broadstreet-v3.0.7.tar.gz
3.0.8	https://card.mcmaster.ca/download/0/broadstreet-v3.0.8.tar.bz2
3.0.9	https://card.mcmaster.ca/download/0/broadstreet-v3.0.9.tar.bz2
3.1.0	https://card.mcmaster.ca/download/0/broadstreet-v3.1.0.tar.bz2
5.1.0	https://card.mcmaster.ca/download/1/software-v5.1.1.tar.bz2">DOWNLOAD</a></td></tr><div id="other-software" class="more collapse"><tr class="more-software collapse"><td>RGI Software</td><td class="hidden-xs">RGI version 5.1.0 - added beta version for K-mer taxonomic classifiers (rgi kmer_build and rgi kmer_query), updated the code to accept a broader range of nucleotide redundancy codes, and set biopython to version 1.72 due to bug on biopython version 1.74</td><td class="hidden-xs">5.1.0</td><td class="hidden-xs">TAR</td><td class="hidden-xs">2019-08-22 09:43:12.5152</td><td><a href="/download/1/software-v5.1.0.tar.gz
Getting version 5.1.0
Working in temporary directory /Users/timothyread/staphopia_dataset/datasets/ariba/card.download
Downloading data from card: https://card.mcmaster.ca/download/1/software-v5.1.1.tar.bz2">DOWNLOAD</a></td></tr><div id="other-software" class="more collapse"><tr class="more-software collapse"><td>RGI Software</td><td class="hidden-xs">RGI version 5.1.0 - added beta version for K-mer taxonomic classifiers (rgi kmer_build and rgi kmer_query), updated the code to accept a broader range of nucleotide redundancy codes, and set biopython to version 1.72 due to bug on biopython version 1.74</td><td class="hidden-xs">5.1.0</td><td class="hidden-xs">TAR</td><td class="hidden-xs">2019-08-22 09:43:12.5152</td><td><a href="/download/1/software-v5.1.0.tar.gz
syscall: wget -O card.tar.bz2 https://card.mcmaster.ca/download/1/software-v5.1.1.tar.bz2">DOWNLOAD</a></td></tr><div id="other-software" class="more collapse"><tr class="more-software collapse"><td>RGI Software</td><td class="hidden-xs">RGI version 5.1.0 - added beta version for K-mer taxonomic classifiers (rgi kmer_build and rgi kmer_query), updated the code to accept a broader range of nucleotide redundancy codes, and set biopython to version 1.72 due to bug on biopython version 1.74</td><td class="hidden-xs">5.1.0</td><td class="hidden-xs">TAR</td><td class="hidden-xs">2019-08-22 09:43:12.5152</td><td><a href="/download/1/software-v5.1.0.tar.gz
The following command failed with exit code 4
wget -O card.tar.bz2 https://card.mcmaster.ca/download/1/software-v5.1.1.tar.bz2">DOWNLOAD</a></td></tr><div id="other-software" class="more collapse"><tr class="more-software collapse"><td>RGI Software</td><td class="hidden-xs">RGI version 5.1.0 - added beta version for K-mer taxonomic classifiers (rgi kmer_build and rgi kmer_query), updated the code to accept a broader range of nucleotide redundancy codes, and set biopython to version 1.72 due to bug on biopython version 1.74</td><td class="hidden-xs">5.1.0</td><td class="hidden-xs">TAR</td><td class="hidden-xs">2019-08-22 09:43:12.5152</td><td><a href="/download/1/software-v5.1.0.tar.gz

The output was:

--2020-08-11 19:48:30--  https://card.mcmaster.ca/download/1/software-v5.1.1.tar.bz2%3EDOWNLOAD%3C/a%3E%3C/td%3E%3C/tr%3E%3Cdiv%20id=other-software%20class=more
Resolving card.mcmaster.ca (card.mcmaster.ca)... 130.113.77.126
Connecting to card.mcmaster.ca (card.mcmaster.ca)|130.113.77.126|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-11 19:48:30 ERROR 404: Not Found.

--2020-08-11 19:48:30--  http://collapse%3E%3Ctr%20class=more-software/
Resolving collapse><tr class=more-software (collapse><tr class=more-software)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘collapse><tr class=more-software’
--2020-08-11 19:48:30--  http://collapse%3E%3Ctd%3Ergi%20software%3C/td%3E%3Ctd%20class=hidden-xs%3ERGI%20version%205.1.0%20-%20added%20beta%20version%20for%20K-mer%20taxonomic%20classifiers%20(rgi%20kmer_build%C2%A0and%C2%A0rgi%20kmer_query),%20updated%20the%20code%20to%20accept%20a%20broader%20range%20of%20nucleotide%20redundancy%20codes,%20and%20set%20biopython%20to%20version%201.72%20due%20to%20bug%20on%20biopython%20version%201.74%3C/td%3E%3Ctd%20class=hidden-xs%3E5.1.0%3C/td%3E%3Ctd%20class=hidden-xs%3ETAR%3C/td%3E%3Ctd%20class=hidden-xs%3E2019-08-22%2009:43:12.5152%3C/td%3E%3Ctd%3E%3Ca%20href=/download/1/software-v5.1.0.tar.gz
Resolving collapse><td>rgi software< (collapse><td>rgi software<)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘collapse><td>rgi software<’
```

**Comment by rpetit3** [comment]
Looks like RGI is being downloaded instead of CARD. Created an issue on Ariba's side to help get this fixed. https://github.com/sanger-pathogens/ariba/issues/301

**Comment by rpetit3** [comment]
Submitted potential fixes:

https://github.com/sanger-pathogens/ariba/pull/302
https://github.com/sanger-pathogens/ariba/pull/303

**Comment by tanaes** [comment]
I'm also getting this error when setting up the global dataset install... Thanks for identifying and submitting a patch for the issue so quickly! 

Is there a way to get around this for installing the general datasets while the regex gets fixed on ARIBA?

**Comment by rpetit3** [comment]
Easiest would be give `--ariba vfdb_core` (removes card from the list to setup). I think I'll add a `--skip_ariba` parameter, in next version update.  Also if card download is not situated, I'll remove it from the defaults.

Let me know if you run into anything else!

**Comment by rpetit3** [comment]
Example using @plasmid02 command above:

Original
```
bactopia datasets datasets --ariba "vfdb_core, card" \
    --species "Staphylococcus aureus" \
    --accessions complete_genome_projects \
    --cpus 4
```

Fixed:
```
bactopia datasets datasets --ariba "vfdb_core" \
    --species "Staphylococcus aureus" \
    --accessions complete_genome_projects \
    --cpus 4
```

**Comment by tanaes** [comment]
Thanks, that worked for me!

**Comment by rpetit3** [comment]
Glad that worked for you!

I've submitted a new release for [v1.4.3](https://github.com/bactopia/bactopia/releases/tag/v1.4.3), that removes (temporarily) CARD as a default ariba dataset, also added the `--skip_ariba` option.

It will probably be a few hours before its synced to Bioconda.

**Comment by tauqeer9** [comment]
Worked for me as well. What are the other options at --ariba?

**Comment by rpetit3** [comment]
Here's what's avialble: https://github.com/sanger-pathogens/ariba/wiki/Task:-getref#usage

```
argannot
card
ncbi
megares
plasmidfinder
resfinder
srst2_argannot
vfdb_core
vfdb_full
virulencefinder
```

**Comment by rpetit3** [comment]
Update! I've submitted patches to the Bioconda recipe, see: https://github.com/bioconda/bioconda-recipes/pull/24010

**Comment by rpetit3** [comment]
This is fixed now.

In your Bactopia conda environment, you will need to update Ariba.

```
conda update -c conda-forge -c bioconda ariba
```

You should see something like:

```
The following packages will be UPDATED:

  ariba                               2.14.5-py36hf0b53f7_1 --> 2.14.5-py36hf0b53f7_2
```

You can now rerun `bactopia datasets` with card

```
bactopia datasets datasets --ariba "card"
2020-08-20 15:22:28:root:INFO - Setting up Ariba datasets
2020-08-20 15:22:28:root:INFO - Setting up card Ariba dataset
2020-08-20 15:23:10:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2020-08-20 15:23:10:root:INFO - datasets/minmer/genbank-k21.json.gz exists, skipping
2020-08-20 15:23:10:root:INFO - datasets/minmer/genbank-k31.json.gz exists, skipping
2020-08-20 15:23:10:root:INFO - datasets/minmer/genbank-k51.json.gz exists, skipping
2020-08-20 15:23:10:root:INFO - datasets/minmer/refseq-k21-s1000.msh exists, skipping
2020-08-20 15:23:10:root:INFO - Setting up pre-computed PLSDB (plasmids) datasets
2020-08-20 15:23:10:root:INFO - datasets/plasmid exists, skipping
2020-08-20 15:23:10:root:INFO - No requests for an species, skipping
2020-08-20 15:23:10:root:INFO - Writing summary of available datasets
```

I will be adding card back as a default Ariba database

**Comment by rpetit3** [comment]
Going to close, feel free to reopen if the issue pops up again
