### ISSUE TITLE
[bug] Bactopia Datasets - Ariba fails to download PubMLST schemas

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#118]
**Description**
There has been a change in the URL for allele fasta downloads at PubMLST. This causes `bactopia datasets` to fail

**Steps to Reproduce**

```
bactopia datasets datasets --ariba "vfdb_core" --species "Staphylococcus aureus" --include_genus --cpus 8

2020-08-17 15:43:24:root:INFO - Staphylococcus aureus verified in ENA Taxonomy database
2020-08-17 15:43:24:root:INFO - Setting up Ariba datasets
2020-08-17 15:43:24:root:INFO - Setting up vfdb_core Ariba dataset
2020-08-17 15:48:49:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2020-08-17 15:49:11:root:INFO - Setting up pre-computed PLSDB (plasmids) datasets
2020-08-17 15:49:51:root:INFO - Setting up MLST datasets
2020-08-17 15:49:51:root:INFO - Setting up default MLST schema for Staphylococcus aureus
2020-08-17 15:49:51:root:INFO - Creating Ariba MLST dataset
Traceback (most recent call last):
  File "/opt/anaconda3/envs/bactopia/bin/bactopia-datasets.py", line 1053, in <module>
    force=(args.force or args.force_mlst))
  File "/opt/anaconda3/envs/bactopia/bin/bactopia-datasets.py", line 362, in setup_mlst
    execute(f'ariba pubmlstget "{species_request}" {ariba_dir}')
  File "/opt/anaconda3/envs/bactopia/bin/bactopia-datasets.py", line 818, in execute
    command.start()
  File "/opt/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1441, in start
    self.start_once(**kw)
  File "/opt/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1508, in start_once
    self.wait(check=check)
  File "/opt/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1551, in wait
    self.check_errors(check=check)
  File "/opt/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1673, in check_errors
    raise self.error_type(self)
executor.ExternalCommandFailed: External command failed with exit code 1!

Command:
bash -c 'ariba pubmlstget "Staphylococcus aureus" datasets/species-specific/staphylococcus-aureus/mlst/default/ariba'

Standard error:
WARNING: I tried to get the version of spades with: "/opt/anaconda3/envs/bactopia/bin/spades.py --version" and the output didn't match this regular expression: "SPAdes\s+v([0-9\.]+)"
Traceback (most recent call last):
  File "/opt/anaconda3/envs/bactopia/bin/ariba", line 312, in <module>
    args.func(args)
  File "/opt/anaconda3/envs/bactopia/lib/python3.6/site-packages/ariba/tasks/pubmlstget.py", line 11, in run
    preparer.run()
  File "/opt/anaconda3/envs/bactopia/lib/python3.6/site-packages/ariba/pubmlst_ref_preparer.py", line 85, in run
    self._load_fasta_files_and_write_clusters_file(self.mlst_download_dir)
  File "/opt/anaconda3/envs/bactopia/lib/python3.6/site-packages/ariba/pubmlst_ref_preparer.py", line 49, in _load_fasta_files_and_write_clusters_file
    raise Error('Cannot find file "' + infile + '" for gene ' + gene_name)
ariba.pubmlst_ref_preparer.Error: Cannot find file "datasets/species-specific/staphylococcus-aureus/mlst/default/ariba/pubmlst_download/arcC.tfa" for gene arcC
```

**Execution Environment**

- Bactopia Version: 1.4.5
- OS: Debian
- Environment: Conda

**Additional Information**
Tagging @tauqeer9 

Related to https://github.com/sanger-pathogens/ariba/issues/304

**Comment by rpetit3** [comment]
Update! I've submitted patches to the Bioconda recipe, see: bioconda/bioconda-recipes#24010

**Comment by rpetit3** [comment]
This is fixed now.

In your Bactopia conda environment, you will need to update Ariba.

```
conda update -c conda-forge -c bioconda ariba
```

You should see something like:

```
The following packages will be UPDATED:

  ariba                               2.14.5-py36hf0b53f7_1 --> 2.14.5-py36hf0b53f7_2
```

After the update, you might need to tack on `--force_mlst` to your command.

```
bactopia datasets datasets --ariba "vfdb_core" --species "Staphylococcus aureus" --include_genus --cpus 8 --force_mlst
2020-08-20 15:19:04:root:INFO - Staphylococcus aureus verified in ENA Taxonomy database
2020-08-20 15:19:04:root:INFO - Setting up Ariba datasets
2020-08-20 15:19:04:root:INFO - vfdb_core (datasets/ariba/vfdb_core) exists, skipping
2020-08-20 15:19:04:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2020-08-20 15:19:04:root:INFO - datasets/minmer/genbank-k21.json.gz exists, skipping
2020-08-20 15:19:04:root:INFO - datasets/minmer/genbank-k31.json.gz exists, skipping
2020-08-20 15:19:04:root:INFO - datasets/minmer/genbank-k51.json.gz exists, skipping
2020-08-20 15:19:04:root:INFO - datasets/minmer/refseq-k21-s1000.msh exists, skipping
2020-08-20 15:19:04:root:INFO - Setting up pre-computed PLSDB (plasmids) datasets
2020-08-20 15:19:04:root:INFO - datasets/plasmid exists, skipping
2020-08-20 15:19:04:root:INFO - Setting up MLST datasets
2020-08-20 15:19:04:root:INFO - --force, removing existing Staphylococcus aureussetup
2020-08-20 15:19:04:root:INFO - Setting up default MLST schema for Staphylococcus aureus
2020-08-20 15:19:04:root:INFO - Creating Ariba MLST dataset
2020-08-20 15:19:41:root:INFO - Creating BLAST MLST dataset
2020-08-20 15:19:42:root:INFO - Setting up custom Prokka proteins
2020-08-20 15:19:42:root:INFO - Setting up custom Prokka proteins for Staphylococcus aureus
2020-08-20 15:19:42:root:INFO - Downloading completed genomes
...
```
