### ISSUE TITLE
[bug] ncbi-genome-download complains out of space (SLURM cluster)

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#119]
**Description**
First I think this is completely a permission issue on our slurm cluster. When a ncbi-genome-download tries to download the cache file, it receives a no space left error.

If the cache is disabled it works fine.

**Steps to Reproduce**
```
  DEBUG: Checking for a cached summary file
  DEBUG: Downloading summary for 'refseq'/'bacteria' uri: 'https://ftp.ncbi.nih.gov/genomes'
  DEBUG: Starting new HTTPS connection (1): ftp.ncbi.nih.gov:443
  DEBUG: https://ftp.ncbi.nih.gov:443 "GET /genomes/refseq/bacteria/assembly_summary.txt HTTP/1.1" 200 None
  Traceback (most recent call last):
    File "/opt/conda/envs/bactopia-gather_fastqs/bin/ncbi-genome-download", line 10, in <module>
      sys.exit(main())
    File "/opt/conda/envs/bactopia-gather_fastqs/lib/python3.8/site-packages/ncbi_genome_download/__main__.py", line 26, in main
      ret = args_download(args)
    File "/opt/conda/envs/bactopia-gather_fastqs/lib/python3.8/site-packages/ncbi_genome_download/core.py", line 174, in args_download
      return config_download(config)
    File "/opt/conda/envs/bactopia-gather_fastqs/lib/python3.8/site-packages/ncbi_genome_download/core.py", line 193, in config_download
      download_candidates = select_candidates(config)
    File "/opt/conda/envs/bactopia-gather_fastqs/lib/python3.8/site-packages/ncbi_genome_download/core.py", line 287, in select_candidates
      summary_file = get_summary(config.section, group, config.uri, config.use_cache)
    File "/opt/conda/envs/bactopia-gather_fastqs/lib/python3.8/site-packages/ncbi_genome_download/core.py", line 400, in get_summary
      fh.write(req.text)
    File "/opt/conda/envs/bactopia-gather_fastqs/lib/python3.8/codecs.py", line 721, in write
      return self.writer.write(data)
    File "/opt/conda/envs/bactopia-gather_fastqs/lib/python3.8/codecs.py", line 378, in write
      self.stream.write(data)
  OSError: [Errno 28] No space left on device

```

**Expected Behavior**
The cache to work as normal.

**Execution Environment**

- Bactopia Version: 1.4.5
- OS: Debian 
- Environment: SLURM cluster (I think this is the issue,(permissions))

**Additional Information**
Using the `--no_cache` option from Bactopia allows things to proceed as normal.

**Comment by rpetit3** [comment]
Will need to be investigated on our end, but `--no_cache` works and is available in https://github.com/bactopia/bactopia/releases/tag/v1.4.7
