### ISSUE TITLE
setup-datasets: ImportError: libcrypto.so.1.0.0 ...

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#12]
During setup-datasets, ariba will produce an error.
```
ariba getref --help
Traceback (most recent call last):
  File "/home/rpetit/miniconda3/envs/ariba/bin/ariba", line 3, in <module>
    import ariba
  File "/home/rpetit/miniconda3/envs/ariba/lib/python3.6/site-packages/ariba/__init__.py", line 57, in <module>
    from ariba import *
  File "/home/rpetit/miniconda3/envs/ariba/lib/python3.6/site-packages/ariba/assembly.py", line 6, in <module>
    from ariba import common, mapping, bam_parse, external_progs, ref_seq_chooser
  File "/home/rpetit/miniconda3/envs/ariba/lib/python3.6/site-packages/ariba/mapping.py", line 4, in <module>
    import pysam
  File "/home/rpetit/miniconda3/envs/ariba/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

It is related to https://github.com/bioconda/bioconda-recipes/pull/17448

And a PR fix has been submitted: https://github.com/bioconda/bioconda-recipes/pull/17448

A temporary fix is to manually upgrade pysam

```
conda activate bactopia
conda install -c conda-forge -c bioconda pysam=0.15.3
```

**Comment by rpetit3** [comment]
This should now be fixed as of v1.1.0 conda release. See PR https://github.com/bioconda/bioconda-recipes/pull/17567
