### ISSUE TITLE
[bug] bactopia tools fastani fails

### ISSUE THREAD

**Issue by tanaes** [bactopia/bactopia#126]
**Description**

Trying to run `bactopia tools fastani` and not getting very far:

```
 bactopia tools fastani --bactopia 20200218_HackFlex_test -qs 12
N E X T F L O W  ~  version 20.07.1
Launching `/home/jgs286/miniconda3/envs/bactopia/share/bactopia-1.4.x/tools/fastani/main.nf` [compassionate_meitner] - revision: 6407f26d67
bactopia tools fastani - 1.4.5
Cannot invoke method isInteger() on null object

 -- Check script '/home/jgs286/miniconda3/envs/bactopia/share/bactopia-1.4.x/tools/fastani/main.nf' at line: 286 or see '.nextflow.log' file for more details
```

The tail of the .nextflow.log file reads:

```
Aug-19 22:13:04.870 [main] DEBUG nextflow.cli.Launcher - $> nextflow run /home/jgs286/miniconda3/envs/bactopia//share/bactopia-1.4.x/tools/fastani/main.nf --bactopia 20200218_HackFlex_test -qs 12
Aug-19 22:13:05.004 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 20.07.1
Aug-19 22:13:05.057 [main] INFO  nextflow.cli.CmdRun - Launching `/home/jgs286/miniconda3/envs/bactopia/share/bactopia-1.4.x/tools/fastani/main.nf` [evil_ritchie] - revision: 6407f26d67
Aug-19 22:13:05.088 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/jgs286/miniconda3/envs/bactopia/share/bactopia-1.4.x/tools/fastani/nextflow.config
Aug-19 22:13:05.089 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/jgs286/miniconda3/envs/bactopia/share/bactopia-1.4.x/tools/fastani/nextflow.config
Aug-19 22:13:05.123 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Aug-19 22:13:06.546 [main] DEBUG nextflow.Session - Session uuid: 5b159ae8-347d-495a-8754-155e72a051f3
Aug-19 22:13:06.547 [main] DEBUG nextflow.Session - Run name: evil_ritchie
Aug-19 22:13:06.551 [main] DEBUG nextflow.Session - Executor pool size: 64
Aug-19 22:13:06.663 [main] DEBUG nextflow.cli.CmdRun -
  Version: 20.07.1 build 5412
  Created: 24-07-2020 15:18 UTC (11:18 EDT)
  System: Linux 3.10.0-957.10.1.el7.x86_64
  Runtime: Groovy 2.5.11 on OpenJDK 64-Bit Server VM 1.8.0_152-release-1056-b12
  Encoding: UTF-8 (UTF-8)
  Process: 258988@cbsumoeller [128.84.180.20]
  CPUs: 64 - Mem: 471.8 GB (33.2 GB) - Swap: 16 GB (14.5 GB)
Aug-19 22:13:06.743 [main] DEBUG nextflow.Session - Work-dir: /local/workdir/jgs/data/isolate_genomes/bactopia/work [xfs]
Aug-19 22:13:06.744 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/jgs286/miniconda3/envs/bactopia/share/bactopia-1.4.x/tools/fastani/bin
Aug-19 22:13:06.831 [main] DEBUG nextflow.Session - Observer factory: TowerFactory
Aug-19 22:13:06.833 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Aug-19 22:13:07.090 [main] DEBUG nextflow.Session - Session start invoked
Aug-19 22:13:07.098 [main] DEBUG nextflow.trace.TraceFileObserver - Flow starting -- trace file: /local/workdir/jgs/data/isolate_genomes/bactopia/bactopia-tools/fastani/fastani/bactopia-info/fastani-trace.txt
Aug-19 22:13:07.638 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Aug-19 22:13:07.651 [main] DEBUG nextflow.Session - Workflow process names [dsl1]: merge_results, collect_assemblies, calculate_ani
Aug-19 22:13:07.660 [main] INFO  nextflow.Nextflow - bactopia tools fastani - 1.4.5
Aug-19 22:13:07.690 [main] DEBUG nextflow.Session - Session aborted -- Cause: Cannot invoke method isInteger() on null object
Aug-19 22:13:07.704 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.NullPointerException: Cannot invoke method isInteger() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:43)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
```

Wondering about this line: `Script base path does not exist or is not a directory:  /home/jgs286/miniconda3/envs/bactopia/share/bactopia-1.4.x/tools/fastani/bin`

It doesn't look like there's a directory `bin` at that path -- should there be?

**Comment by rpetit3** [comment]
Should be fixed: https://github.com/bactopia/bactopia/commit/12ed3ce7f10ad8200ffc129a150c2b76b7fe8458

Issue was the limit (for max ncbi-genome-download downloads) defaults as `null`, but it was being tested if it was an integer. 

I'll push a version update in the morning (EST time)

**Comment by tanaes** [comment]
Great, thanks!

**Comment by rpetit3** [comment]
If you don't want to wait, a quick fix is to set `--limit 10000` or some arbitrary positive integer

**Comment by tanaes** [comment]
*Excellent,* thanks!

**Comment by tanaes** [comment]
Bummer, no luck:

```
    Bactopia Tool 'fastani' - Execution Summary
    ---------------------------
    Command Line    : nextflow run /home/jgs286/miniconda3/envs/bactopia//share/bactopia-1.4.x/tools/fastani/main.nf --bactopia 20200218_HackFlex_test --exclude bactopia-tools/summary/bactopia/bactopia-exclude.txt --limit 10000 --force
    Resumed         : false
    Completed At    : 2020-08-20T00:02:08.908-04:00
    Duration        : 6.4s
    Success         : false
    Exit Code       : null
    Error Report    : Error executing process > 'collect_assemblies'

Caused by:
  No such property: reference_file for class: Script7BEAC1156C87B451578D9750252AD39E

Source block:
  is_gzipped = null
  reference_name = null
  if (reference) {
          is_gzipped = params.reference.endsWith(".gz") ? true : false
          reference_name = reference.getSimpleName().replace(".gz", "")
          reference_file = reference.getName()
      }
  """ 
      mkdir assemblies samples
      if [ "!{params.species}" != "null" ]; then
          mkdir fasta
          if [ "!{params.limit}" != "null" ]; then
              ncbi-genome-download bacteria -l complete -o ./ -F fasta -p !{task.cpus} \
                                            --genus "!{params.species}" -r 50 --dry-run > accession-list.txt
              shuf accession-list.txt | head -n !{params.limit} > accession-subset.txt
              ncbi-genome-download bacteria -l complete -o ./ -F fasta -p !{task.cpus} \
                                            -A accession-subset.txt -r 50
          else
              ncbi-genome-download bacteria -l complete -o ./ -F fasta -p !{task.cpus} \
                                            --genus "!{params.species}" -r 50
          fi
          find -name "GCF*.fna.gz" | xargs -I {} mv {} fasta/
          rename 's/(GCF_\\d+).*/\$1.fna.gz/' fasta/*
          gunzip fasta/*
          cp fasta/*.fna assemblies/
          ls fasta/ | xargs -I {} cp -P fasta/{} samples/{}.query
      fi

      if [ "!{params.accession}" != "null" ]; then   
          mkdir fasta
          ncbi-genome-download bacteria -l complete -o ./ -F fasta -p !{task.cpus} \
                                        -A !{params.accession} -r 50
          find -name "GCF*.fna.gz" | xargs -I {} mv {} fasta/
          rename 's/(GCF_\\d+).*/\$1.fna.gz/' fasta/*
          gunzip fasta/*
          cp fasta/*.fna assemblies/
          ls fasta/ | xargs -I {} cp -P fasta/{} samples/{}.query
      fi

      if [ "!{params.reference}" != "null" ]; then   
          if [ "!{is_gzipped}" == "true" ]; then
              zcat !{reference_file} > assemblies/!{reference_name}.fna
              cp -P assemblies/!{reference_name}.fna samples/!{reference_name}.fna.query
          else
              cp -P !{reference_file} assemblies/!{reference_name}.fna
              cp -P !{reference_file} samples/!{reference_name}.fna.query
          fi
      fi

      find -name "*.fna.gz" | xargs -I {} gunzip {}  

      if [ "!{params.pairwise}" == "true" ]; then
          cp -f -P *.fna assemblies/
      fi

      ls *.fna | xargs -I {} cp -f -P {} samples/{}.query
      """

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
    Launch Dir      : /local/workdir/jgs/data/isolate_genomes/bactopia
    Working Dir     : /local/workdir/jgs/data/isolate_genomes/bactopia/work (Total Size: 1.023G)
    Working Dir Size: 1.023G
```

**Comment by tanaes** [comment]
No rush, just logging things as I find them. Really appreciate all you're doing! It's an amazing tool!

**Comment by rpetit3** [comment]
Another one, haha I tended to run fastani with a reference to the variable was always set. Fixed: https://github.com/bactopia/bactopia/commit/254d31c903e0fe2c943fdb6f08fef52399924dc4 

Thank you very much!
