### ISSUE TITLE
[question] custom channel not available on anaconda mirror

### ISSUE THREAD

**Issue by koolape** [bactopia/bactopia#178]
**When I ran the following command:**

`bactopia --sample fk --R1 ./FK2159/2_HQData/FK2159.SOAP_cor_R1.fq.gz --R2 ./FK2159/2_HQData/FK2159.SOAP_cor_R2.fq.gz --cpus 6`

**It promted some errors:**

2020-12-20 15:13:02:root:INFO - Found /public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/linux/annotate_genome.yml (1 or 12), begin build to /public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/envs/annotate_genome-1.5.x
2020-12-20 15:26:25:root:INFO - Found /public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/linux/antimicrobial_resistance.yml (2 or 12), begin build to /public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/envs/antimicrobial_resistance-1.5.x
2020-12-20 15:29:01:root:INFO - Found /public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/linux/ariba_analysis.yml (3 or 12), begin build to /public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/envs/ariba_analysis-1.5.x
2020-12-20 15:31:48:root:INFO - Found /public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/linux/assemble_genome.yml (4 or 12), begin build to /public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/envs/assemble_genome-1.5.x
Traceback (most recent call last):
  File "/public/home/Kk/anaconda3/envs/bactopia/bin/bactopia-build.py", line 171, in <module>
    execute(f'conda env create -f {env_file} --prefix {prefix} {force}')
  File "/public/home/Kk/anaconda3/envs/bactopia/bin/bactopia-build.py", line 71, in execute
    command.start()
  File "/public/home/Kk/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1441, in start
    self.start_once(**kw)
  File "/public/home/Kk/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1508, in start_once
    self.wait(check=check)
  File "/public/home/Kk/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1551, in wait
    self.check_errors(check=check)
  File "/public/home/Kk/anaconda3/envs/bactopia/lib/python3.6/site-packages/executor/__init__.py", line 1673, in check_errors
    raise self.error_type(self)
executor.ExternalCommandFailed: External command failed with exit code 1!

Command:
bash -c 'conda env create -f /public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/linux/assemble_genome.yml --prefix /public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/envs/assemble_genome-1.5.x --force'

Standard output:
EnvironmentSectionNotValid: The following section on '/public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/linux/assemble_genome.yml' is invalid and will be ignored:
 - version

Collecting package metadata (repodata.json): ...working... failed

Standard error:
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: rpetit3
  channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/rpetit3
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
N E X T F L O W  ~  version 20.10.0
Launching `/public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/main.nf` [chaotic_borg] - revision: 403ec4cd2e
Can't open cache DB: /public/home/Kk/.nextflow/cache/c63cb94d-e512-4bf2-9481-babcb9b00258/db

Nextflow needs to be executed in a shared file system that supports file locks.
Alternatively you can run it in a local directory and specify the shared work
directory by using by `-w` command line option.

**Because I'm using a anaconda mirror in my country, so I'm wondering if it was caused by the mirror:**
`Standard error:
UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: rpetit3
  channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/rpetit3
  error code: 404`

**Comment by rpetit3** [comment]
Hi @koolape!

Thank you very much for checking in. The issue here is definitely due to the mirror. I maintain a custom version of Shovill that allows single end reads. Here's the branch (https://github.com/rpetit3/shovill/tree/single-end-reads).

If you don't need single end reads, you can edit this file `/public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/linux/assemble_genome.yml`

Remove the line with `- rpetit3` under the channels section (Line 4)(https://github.com/bactopia/bactopia/blob/master/conda/linux/assemble_genome.yml#L4)

You will also need to make a change to `/public/home/Kk/anaconda3/envs/bactopia/share/bactopia-1.5.x/conda/linux/assemble_genome.yml`

In this one you will want to remove two line lines (4 and 13):
`- rpetit3` (https://github.com/bactopia/bactopia/blob/master/conda/linux/gather_fastqs.yml#L4) 
`  - aspera-connect=3.9.6` (https://github.com/bactopia/bactopia/blob/master/conda/linux/gather_fastqs.yml#L13) 

I think that should help you, let me know if not!

**Comment by koolape** [comment]
thanks, but I decided to switch back to the official mirror

**Comment by rpetit3** [comment]
I think you are ok now, if not please feel free to reopen.

**Comment by koolape** [comment]
I'm wondering how many customer channels does Bactopia use and their differences between the original ones.

**Comment by rpetit3** [comment]
Bactopia only uses one customer channel, [rpetit3 (my own)](https://anaconda.org/rpetit3), for two tools [Shovill (with single-end support)](https://anaconda.org/rpetit3/shovill) and [Aspera Connect](https://anaconda.org/rpetit3/aspera-connect).

**Comment by koolape** [comment]
thanks again. I'll try following the instruction above to delete the customer channel since 
1. it is not included in the mirror. BTW The download speed from official channel is really slow in China. Thus I'd like to use a mirror 
2. Currently I don't have to deal withsingle end reads

**Comment by rpetit3** [comment]
I'll see about dropping Aspera Connect, since I'm not sure how much use it will get going forward. I'll also reach out to Torsten Seemann to see if he has any objections to me putting Shovill-SE on Bioconda. 

This I think would fix your problem, and also remove the external dependency.

**Comment by koolape** [comment]
I have set a proxy server in `.condarc` file. If I run `bactopia build --default`, will the build process use the proxy as well?
