### ISSUE TITLE
bactopia datasets issue when setting up vfdb_core Ariba dataset  

### ISSUE THREAD

**Issue by emv6** [bactopia/bactopia#211]
Hi, 

I have recently installed Bactopia on a cluster and the installation with conda occurred with no issues. But when I tried to complete the next step of installing the databases I get the following error with the command bactopia datasets 

```
bactopia datasets
2021-04-12 11:50:46:root:INFO - Setting up Ariba datasets
2021-04-12 11:50:46:root:INFO - Setting up vfdb_core Ariba dataset
External command failed with exit code 1!

Command:
bash -c 'ariba getref vfdb_core vfdb_core'

Standard output:
Downloading "http://www.mgc.ac.cn/VFs/Down/VFDB_setA_nt.fas.gz" and saving as 
"/mnt/raid/emvos0/datasets/ariba/vfdb_core.tmp.download/VFDB_setA_nt.fas.gz" ...Traceback (most recent call last):
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/bin/ariba", line 312, in <module>
    args.func(args)
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/lib/python3.7/site-packages/ariba/tasks/getref.py", line 11, in run
    getter.run(options.outprefix)
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/lib/python3.7/site-packages/ariba/ref_genes_getter.py", line 664, in run
    exec('self._get_from_' + self.ref_db + '(outprefix)')
  File "<string>", line 1, in <module>
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/lib/python3.7/site-packages/ariba/ref_genes_getter.py", line 427, in _get_from_vfdb_core
    self._get_from_vfdb_common(outprefix, 'VFDB_setA_nt.fas.gz','core')
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/lib/python3.7/site-packages/ariba/ref_genes_getter.py", line 444, in _get_from_vfdb_common
    common.download_file('http://www.mgc.ac.cn/VFs/Down/' + filename, zipfile, max_attempts=self.max_download_attempts, sleep_time=self.sleep_time, verbose=True)
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/lib/python3.7/site-packages/ariba/common.py", line 71, in download_file
    raise Error('Error downloading: ' + url)
ariba.common.Error: Error downloading: http://www.mgc.ac.cn/VFs/Down/VFDB_setA_nt.fas.gz

Standard error:
Downloading "http://www.mgc.ac.cn/VFs/Down/VFDB_setA_nt.fas.gz" and saving as "/mnt/raid/emvos0/datasets/ariba/vfdb_core.tmp.download/VFDB_setA_nt.fas.gz" ...Traceback (most recent call last):
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/bin/ariba", line 312, in <module>
    args.func(args)
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/lib/python3.7/site-packages/ariba/tasks/getref.py", line 11, in run
    getter.run(options.outprefix)
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/lib/python3.7/site-packages/ariba/ref_genes_getter.py", line 664, in run
    exec('self._get_from_' + self.ref_db + '(outprefix)')
  File "<string>", line 1, in <module>
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/lib/python3.7/site-packages/ariba/ref_genes_getter.py", line 427, in _get_from_vfdb_core
    self._get_from_vfdb_common(outprefix, 'VFDB_setA_nt.fas.gz','core')
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/lib/python3.7/site-packages/ariba/ref_genes_getter.py", line 444, in _get_from_vfdb_common
    common.download_file('http://www.mgc.ac.cn/VFs/Down/' + filename, zipfile, max_attempts=self.max_download_attempts, sleep_time=self.sleep_time, verbose=True)
  File "/mnt/raid/emvos0/miniconda/envs/bactopia/lib/python3.7/site-packages/ariba/common.py", line 71, in download_file
    raise Error('Error downloading: ' + url)
ariba.common.Error: Error downloading: http://www.mgc.ac.cn/VFs/Down/VFDB_setA_nt.fas.gz
```

I have tried to deactivate the conda environment and activate bactopia again and this error proceeds. Any help anyone can give will be greatly appreciated.

**Comment by rpetit3** [comment]
It might have been an connection issue with VFDB, do you still get the error?

If it persists you can use `--ariba card` to skip downloading VFDB datasets.

**Comment by emv6** [comment]
Yes it does seem to be an issue with the connection to the database but our IT department is looking into why we can't seem to access this database. I tried your solution --ariba card and the databases install successfully so it just seems to be an issue with the VFDB. Thanks for your help

**Comment by emv6** [comment]
This issue has been fixed now

**Comment by nthamilton57** [comment]
I am having this issue with vfdb_full. Was there ever a fix?
