### ISSUE TITLE
[bug] WARN: Unable to resume cached task -- See log file for details

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#212]
**Description**
Nextflow's resume (`-resume`) function is not working

**Steps to Reproduce**
```
bactopia ...params... -resume
```

**Expected Behavior**
Pipelines should resume where they left off at

**Execution Environment**

- Bactopia Version: 1.6.5
- OS: Debian 10
- Environment: SLURM

**Additional Information**
I messed with the work directory, that might be the cause.

**Comment by tanaes** [comment]
Can confirm I've been running into this as well.

**Comment by rpetit3** [comment]
Apologies about that, I'm hoping to get this cleared up in version 2

**Comment by rpetit3** [comment]
I think its related to this
```
Sep-11 04:03:09.826 [Actor Thread 5] WARN  nextflow.processor.TaskProcessor - [BACTOPIA:GATHER_SAMPLES (SRX4563634)] Unable to resume cached task -- See log file for details
com.esotericsoftware.kryo.KryoException: Class cannot be created (missing no-arg constructor): nextflow.util.VersionNumber
	at com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1228)
	at nextflow.util.InstantiationStrategy.newInstantiatorOf(SerializationHelper.groovy:248)
	at com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1049)
	at com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1058)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.create(FieldSerializer.java:547)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:523)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:143)
	at com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:21)
	at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:761)
	at com.esotericsoftware.kryo.Kryo$readClassAndObject$2.call(Unknown Source)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy:182)
	at nextflow.util.KryoHelper.deserialize(SerializationHelper.groovy)
	at nextflow.util.KryoHelper$deserialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.processor.TaskContext.deserialize(TaskContext.groovy:190)
	at nextflow.CacheDB.getTaskEntry(CacheDB.groovy:163)
	at nextflow.CacheDB$getTaskEntry.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at nextflow.processor.TaskProcessor.checkCachedOutput(TaskProcessor.groovy:869)
	at nextflow.processor.TaskProcessor.checkCachedOrLaunchTask(TaskProcessor.groovy:758)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:203)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:592)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:59)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Which might be related to how the inputs work on that process, going to reach out to NF team

**Comment by rpetit3** [comment]
Hey! Figured it out! Issue was in `gather_fastqs` (or `gather_samples` in v2) I was asking for Nextflow version which it did not like for some reason. After removing that, we can resume again.
```
[f9/8fb0ff] process > BACTOPIA:GATHER_SAMPLES (SRX4563634) [100%] 1 of 1, cached: 1 ✔
[18/57e2ee] process > BACTOPIA:QC_READS (SRX4563634)       [  0%] 0 of 1
```

This will be fixed in v2

**Comment by tanaes** [comment]
Huzzah! Thanks!

**Comment by rpetit3** [comment]
No problem! I know how frustrating this issue can be! 

Hoping to get v2 out before the end of the month, so not too much longer

**Comment by rpetit3** [comment]
Hi @tanaes 

I've release v2 (https://github.com/bactopia/bactopia/releases/tag/v2.0.0) and this should now be fixed.  Please let me know if it still persists for you!

Cheers!
Robert

**Comment by tanaes** [comment]
Great, thanks! Looking forward to trying it out.
