### ISSUE TITLE
[bug] unable to call variants

### ISSUE THREAD

**Issue by kimhoang098** [bactopia/bactopia#252]
Hi Robert!

**Description**
Bactopia seemed to be running until it gets to the calling variants against the reference genome (user-populated) step, where it attempts it a few times but without success. 

**Steps to Reproduce**
Ran Bactopia with --skip_amr and --disable_auto_variants

When the error started:
executor >  local (16)
[6a/55a225] process > gather_fastqs (A11)            [100%] 1 of 1 ✔
[d4/097fd0] process > fastq_status (1)               [100%] 1 of 1 ✔
[6f/a97ee1] process > estimate_genome_size (A11)     [100%] 1 of 1 ✔
[70/9056f4] process > qc_reads (A11)                 [100%] 1 of 1 ✔
[d7/d1da75] process > qc_original_summary (A11)      [100%] 1 of 1 ✔
[b1/7d8f11] process > qc_final_summary (A11)         [100%] 1 of 1 ✔
[-        ] process > assemble_genome (A11)          -
[-        ] process > assembly_qc                    -
[-        ] process > make_blastdb                   -
[-        ] process > annotate_genome                -
[d6/d14984] process > count_31mers (A11)             [100%] 1 of 1 ✔
[-        ] process > sequence_type                  -
[f1/9ee1c1] process > ariba_analysis (A11 - vfdb_... [100%] 2 of 2 ✔
[bf/9a8ba7] process > minmer_sketch (A11)            [100%] 1 of 1 ✔
[-        ] process > minmer_query                   -
[28/b99ed1] process > call_variants (A11 - ancest... [100%] 4 of 4, failed: 4...
[-        ] process > download_references            -
[-        ] process > call_variants_auto             -
[-        ] process > antimicrobial_resistance       -
[-        ] process > blast_primers                  -
[-        ] process > blast_proteins                 -
[2f/0428e9] process > mapping_query (A11})           [100%] 1 of 1 ✔
Error executing process > 'call_variants (A11 - ancestor_simple)'

Caused by:
  Process `call_variants (A11 - ancestor_simple)` terminated with an error exit status (1)

Command executed [/home/zool2483/.conda/envs/bactopia/share/bactopia-1.7.x/templates/call_variants.sh]:

  #!/bin/bash
  set -e
  set -u
  LOG_DIR="call_variants"
  mkdir -p ${LOG_DIR}
  echo "# Timestamp" > ${LOG_DIR}/call_variants.versions
  date --iso-8601=seconds >> ${LOG_DIR}/call_variants.versions
  echo "# Snippy Version" >> ${LOG_DIR}/call_variants.versions
  snippy --version >> ${LOG_DIR}/call_variants.versions 2>&1
  
  # Print captured STDERR incase of exit
  function print_stderr {
      cat .command.err 1>&2
      ls ${LOG_DIR}/ | grep ".err" | xargs -I {} cat ${LOG_DIR}/{} 1>&2
  }
  trap print_stderr EXIT
  
  # Verify AWS files were staged
  if [[ ! -L "A11_R1.fastq.gz" ]]; then
      if [ "false" == "true" ]; then
          check-staging.py --fq1 A11_R1.fastq.gz --extra ancestor_simple.fasta --is_single
      else
          check-staging.py --fq1 A11_R1.fastq.gz --fq2 A11_R2.fastq.gz --extra ancestor_simple.fasta
      fi
  fi
  
  snippy --R1 A11_R1.fastq.gz --R2 A11_R2.fastq.gz \
      --ref ancestor_simple.fasta \
      --cpus 2 \
      --ram 16 \
      --outdir ancestor_simple \
      --prefix A11 \
      --mapqual 60 \
      --basequal 13 \
      --mincov 10 \
      --minfrac 0 \
      --minqual 100 \
      --maxsoft 10   > ${LOG_DIR}/snippy.out 2> ${LOG_DIR}/snippy.err
  
  # Add GenBank annotations
  echo "# vcf-annotator Version" >> ${LOG_DIR}/call_variants.versions
  vcf-annotator --version >> ${LOG_DIR}/call_variants.versions 2>&1
  vcf-annotator ancestor_simple/A11.vcf ancestor_simple.fasta > ancestor_simple/A11.annotated.vcf 2> ${LOG_DIR}/vcf-annotator.err
  
  # Get per-base coverage
  echo "# bedtools Version" >> ${LOG_DIR}/call_variants.versions
  bedtools --version >> ${LOG_DIR}/call_variants.versions 2>&1
  grep "^##contig" ancestor_simple/A11.vcf > ancestor_simple/A11.full-coverage.txt
  genomeCoverageBed -ibam ancestor_simple/A11.bam -d >> ancestor_simple/A11.full-coverage.txt 2> ${LOG_DIR}/genomeCoverageBed.err
  cleanup-coverage.py ancestor_simple/A11.full-coverage.txt > ancestor_simple/A11.coverage.txt
  rm ancestor_simple/A11.full-coverage.txt
  
  # Mask low coverage regions
  mask-consensus.py A11 ancestor_simple \
                      ancestor_simple/A11.consensus.subs.fa \
                      ancestor_simple/A11.subs.vcf \
                      ancestor_simple/A11.coverage.txt \
                      --mincov 10 > ancestor_simple/A11.consensus.subs.masked.fa 2> ${LOG_DIR}/mask-consensus.err
  
  # Clean Up
  rm -rf ancestor_simple/reference ancestor_simple/ref.fa* ancestor_simple/A11.vcf.gz*
  
  if [[ false == "true" ]]; then
      find ancestor_simple/ -type f -not -name "*.bam*" -and -not -name "*.log*" -and -not -name "*.txt*" | \
          xargs -I {} pigz -n --best -p 2 {}
      pigz -n --best -p 2 ancestor_simple/A11.coverage.txt
  fi
  
  if [ "false" == "false" ]; then 
      cp .command.err ${LOG_DIR}/call_variants.err
      cp .command.out ${LOG_DIR}/call_variants.out
      cp .command.sh ${LOG_DIR}/call_variants.sh || :
      cp .command.trace ${LOG_DIR}/call_variants.trace || :
  else
      rm -rf ${LOG_DIR}/
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:
         total no. variants observed              : 1
         total no. reference observed             : 0
  
  Time elapsed: 0.00s
  
  [10:51:16] Running: cp A11.filt.vcf A11.vcf 2>> A11.log
  [10:51:16] Running: /home/zool2483/.conda/envs/bactopia/share/bactopia-1.7.x/conda/envs/call_variants-1.7.x/bin/snippy-vcf_to_tab --gff reference/ref.gff --ref reference/ref.fa --vcf A11.vcf > A11.tab 2>> A11.log
  [10:51:17] Running: /home/zool2483/.conda/envs/bactopia/share/bactopia-1.7.x/conda/envs/call_variants-1.7.x/bin/snippy-vcf_extract_subs A11.filt.vcf > A11.subs.vcf 2>> A11.log
  [10:51:17] Running: bcftools convert -Oz -o A11.vcf.gz A11.vcf 2>> A11.log
  [10:51:17] Running: bcftools index -f A11.vcf.gz 2>> A11.log
  [10:51:17] Running: bcftools consensus --sample ancestor_simple -f reference/ref.fa -o A11.consensus.fa A11.vcf.gz 2>> A11.log
  [10:51:17] Running: bcftools convert -Oz -o A11.subs.vcf.gz A11.subs.vcf 2>> A11.log
  [10:51:17] Running: bcftools index -f A11.subs.vcf.gz 2>> A11.log
  [10:51:17] Running: bcftools consensus --sample ancestor_simple -f reference/ref.fa -o A11.consensus.subs.fa A11.subs.vcf.gz 2>> A11.log
  [10:51:17] Running: rm -f A11.subs.vcf.gz A11.subs.vcf.gz.csi A11.subs.vcf.gz.tbi 2>> A11.log
  [10:51:17] Generating reference aligned/masked FASTA relative to reference: A11.aligned.fa
  [10:51:26] Marked 1865 heterozygous sites with 'n'
  [10:51:26] Creating extra output files: BED GFF CSV TXT HTML
  [10:51:26] Identified 1 variants.
  [10:51:26] Result folder: ancestor_simple
  [10:51:26] Result files:
  [10:51:26] * ancestor_simple/A11.aligned.fa
  [10:51:26] * ancestor_simple/A11.bam
  [10:51:26] * ancestor_simple/A11.bam.bai
  [10:51:26] * ancestor_simple/A11.bed
  [10:51:26] * ancestor_simple/A11.consensus.fa
  [10:51:26] * ancestor_simple/A11.consensus.subs.fa
  [10:51:26] * ancestor_simple/A11.csv
  [10:51:26] * ancestor_simple/A11.filt.vcf
  [10:51:26] * ancestor_simple/A11.gff
  [10:51:26] * ancestor_simple/A11.html
  [10:51:26] * ancestor_simple/A11.log
  [10:51:26] * ancestor_simple/A11.raw.vcf
  [10:51:26] * ancestor_simple/A11.subs.vcf
  [10:51:26] * ancestor_simple/A11.tab
  [10:51:26] * ancestor_simple/A11.txt
  [10:51:26] * ancestor_simple/A11.vcf
  [10:51:26] * ancestor_simple/A11.vcf.gz
  [10:51:26] * ancestor_simple/A11.vcf.gz.csi
  [10:51:26] Walltime used: 2 minutes, 41 seconds
  [10:51:26] Have a suggestion? Tell me at https://github.com/tseemann/snippy/issues
  [10:51:26] Done.
  Traceback (most recent call last):
    File "/home/zool2483/.conda/envs/bactopia/share/bactopia-1.7.x/conda/envs/call_variants-1.7.x/bin/vcf-annotator", line 393, in <module>
      annotator.annotate_vcf_records()
    File "/home/zool2483/.conda/envs/bactopia/share/bactopia-1.7.x/conda/envs/call_variants-1.7.x/bin/vcf-annotator", line 67, in annotate_vcf_records
      self.__gb.accession = record.CHROM
    File "/home/zool2483/.conda/envs/bactopia/share/bactopia-1.7.x/conda/envs/call_variants-1.7.x/bin/vcf-annotator", line 220, in accession
      self.__gb = self.records[value]
  KeyError: 'c_000000000001'

Work dir:
  /data/zool-pa14-genomics/zool2483/work/bactopia/28/b99ed1e370a5a5e9f407bb34763e6f

**Expected Behavior**
Call variants against user-populated reference genome

**Execution Environment**

- Bactopia Version: 1.7.1
- OS: compute clusters operating on Linux
- Environment: conda

Thanks very much!

**Comment by rpetit3** [comment]
Hi @kimhoang098!

This looks related to https://github.com/rpetit3/vcf-annotator/issues/9

I'll be sure to fix this in v2, but for now you can try
```
conda activate  /home/zool2483/.conda/envs/bactopia/share/bactopia-1.7.x/conda/envs/call_variants-1.7.x/
conda install -c conda-forge -c bioconda 'vcf-annotator=0.7'
```

Let me know if that works for you!

Cheers,
Robert

**Comment by kimhoang098** [comment]
Thanks, Robert! I ran it again after trying what you suggested and still got the same error. It will finish the run if there are no files in the reference-genomes and mapping-sequences directories, so it's a quick fix for now.

**Comment by rpetit3** [comment]
@kimhoang098 I'm going to close this for now, but by chance do you have a genbank  and VCF file you can share? I'd like to get this fixed on the `vcf-annotator` side of things

**Comment by kimhoang098** [comment]
Hi Robert, 

Unfortunately it didn’t get as far as creating a VCF file, and the reference genome I was using is not on GenBank yet. Thank you for looking into it though!

Kim

**Comment by rpetit3** [comment]
No problem! Let me know if you want me to update `vcf-annotator` to work with your reference. I think it's just using a naming format I haven't accommodated for, so it should be straight forward. For this I'll just need the reference genbank file.
