### ISSUE TITLE
Failed to download assembly_qc.yml --prefix  ： External command failed with exit code 1!

### ISSUE THREAD

**Issue by plasminogene** [bactopia/bactopia#294]
Hi，

I failed to download assembly_qc.yml --prefix ，error is posted below.

Thanks

Haitao
```
(bactopia) prp27@ubuntu:~$  bactopia download --build_all
2022-03-10 00:49:10:root:INFO - Checking if environment pre-builds are needed, use --verbose to see full details.
2022-03-10 00:49:10:root:INFO - Found /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/assembly_qc.yml (3 of 7), begin build to /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/assembly_qc-2.0.x
External command failed with exit code 1!

Command:
bash -c 'mamba env create -f /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/assembly_qc.yml --prefix /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/assembly_qc-2.0.x --force'

Standard error:
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 88, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/constructor.py", line 106, in get_single_data
        node = self.composer.get_single_node()
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 101, in compose_document
        node = self.compose_node(None, None)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 138, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 217, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 136, in compose_node
        node = self.compose_sequence_node(anchor)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 178, in compose_sequence_node
        while not self.parser.check_event(SequenceEndEvent):
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 141, in check_event
        self.current_event = self.state()
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 513, in parse_block_sequence_entry
        raise ParserError(
    ruamel_yaml.parser.ParserError: while parsing a block collection
      in "<unicode string>", line 3, column 3:
          - conda config --add channels ht ... 
          ^ (line: 3)
    expected <block end>, but found '?'
      in "<unicode string>", line 7, column 3:
          dependencies:
          ^ (line: 7)

`$ /home/prp27/anaconda3/envs/bactopia/bin/mamba create -f /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/assembly_qc.yml --prefix /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/assembly_qc-2.0.x --force`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=bactopia
                CONDA_EXE=/home/prp27/anaconda3/bin/conda
             CONDA_PREFIX=/home/prp27/anaconda3/envs/bactopia
           CONDA_PREFIX_1=/home/prp27/anaconda3
    CONDA_PROMPT_MODIFIER=(bactopia)
         CONDA_PYTHON_EXE=/home/prp27/anaconda3/bin/python
               CONDA_ROOT=/home/prp27/anaconda3/envs/bactopia
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/home/prp27/anaconda3/envs/bactopia/lib/server
                     PATH=/home/prp27/anaconda3/envs/bactopia/bin:/home/prp27/anaconda3/condabin
                          :/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/gam
                          es:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/prp27/anaconda3/envs/bactopia
            shell level : 2
       user config file : /home/prp27/.condarc
 populated config files : /home/prp27/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.10.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/prp27/anaconda3/envs/bactopia  (writable)
      conda av data dir : /home/prp27/anaconda3/envs/bactopia/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/prp27/anaconda3/envs/bactopia/pkgs
                          /home/prp27/.conda/pkgs
       envs directories : /home/prp27/anaconda3/envs/bactopia/envs
                          /home/prp27/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.10 Linux/5.13.0-35-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

An unexpected error has occurred. Conda has prepared the above report.

**Comment by rpetit3** [comment]
Hi @plasminogene 

Let's see if we can get this figured out! Can you see if this works?

```
mamba create -n temp-assembly_qc -c conda-forge -c bioconda quast checkm-genome
```

**Comment by plasminogene** [comment]
yes，it is  work.

**Comment by plasminogene** [comment]
When I used the virtual machine to transfer Ubuntu from disk C to disk D, the bug disappeared.

**Comment by rpetit3** [comment]
That's great! Is that an OK solution for you? 

Would you like me to try and figure out what might be happening?

**Comment by plasminogene** [comment]
At least there are no errors. The download speed is very slow.  I'm curious about what happened and what I'm going to do?

**Comment by plasminogene** [comment]
Sorry,I find error.
(bactopia) prp27@ubuntu:~$ bactopia download --build_all
2022-03-10 08:51:45:root:INFO - Checking if environment pre-builds are needed, use --verbose to see full details.
2022-03-10 08:51:45:root:INFO - Found Conda environments in /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs, if a complete rebuild is needed please use --force_rebuild
2022-03-10 08:51:45:root:INFO - Found /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/assembly_qc.yml (3 of 7), begin build to /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/assembly_qc-2.0.x
2022-03-10 09:27:31:root:INFO - Found Conda environments in /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs, if a complete rebuild is needed please use --force_rebuild
2022-03-10 09:27:31:root:INFO - Begin ngmaster create to /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/bioconda--ngmaster-0.5.8
External command failed with exit code 1!

Command:
bash -c 'mamba create -y -p /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/bioconda--ngmaster-0.5.8 -c conda-forge -c bioconda --force bioconda::ngmaster=0.5.8'

Standard output:
__    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.22.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Standard error:
CondaValueError: prefix already exists: /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/bioconda--ngmaster-0.5.8
(bactopia) prp27@ubuntu:~$

**Comment by rpetit3** [comment]
You might need to toss in a `--force_rebuild`

Another option, if available is to use Docker or Singularity.

**Comment by plasminogene** [comment]
I find error when after used--force_rebuild. 

I didn't find the command line of Docker or Singularity in the user manual（ https://bactopia.github.io/）. I need help.Thanks!

(bactopia) prp27@ubuntu:~$ bactopia download --build_all --force_rebuild
2022-03-10 09:46:04:root:INFO - Checking if environment pre-builds are needed, use --verbose to see full details.
2022-03-10 09:46:04:root:INFO - --force_rebuild used, overwriting existing Conda environments in /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs
2022-03-10 09:46:04:root:INFO - Found /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/annotate_genome.yml (1 of 7), begin build to /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/annotate_genome-2.0.x
2022-03-10 09:47:05:root:INFO - Found /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/assemble_genome.yml (2 of 7), begin build to /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/assemble_genome-2.0.x
External command failed with exit code 1!

Command:
bash -c 'mamba env create -f /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/assemble_genome.yml --prefix /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/assemble_genome-2.0.x --force'

Standard error:
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 88, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/constructor.py", line 106, in get_single_data
        node = self.composer.get_single_node()
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 101, in compose_document
        node = self.compose_node(None, None)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 138, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 217, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 136, in compose_node
        node = self.compose_sequence_node(anchor)
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 178, in compose_sequence_node
        while not self.parser.check_event(SequenceEndEvent):
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 141, in check_event
        self.current_event = self.state()
      File "/home/prp27/anaconda3/envs/bactopia/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 513, in parse_block_sequence_entry
        raise ParserError(
    ruamel_yaml.parser.ParserError: while parsing a block collection
      in "<unicode string>", line 3, column 3:
          - conda config --add channels ht ... 
          ^ (line: 3)
    expected <block end>, but found '?'
      in "<unicode string>", line 6, column 3:
          dependencies:
          ^ (line: 6)

`$ /home/prp27/anaconda3/envs/bactopia/bin/mamba create -f /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/assemble_genome.yml --prefix /home/prp27/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/assemble_genome-2.0.x --force`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=bactopia
                CONDA_EXE=/home/prp27/anaconda3/bin/conda
             CONDA_PREFIX=/home/prp27/anaconda3/envs/bactopia
           CONDA_PREFIX_1=/home/prp27/anaconda3
    CONDA_PROMPT_MODIFIER=(bactopia)
         CONDA_PYTHON_EXE=/home/prp27/anaconda3/bin/python
               CONDA_ROOT=/home/prp27/anaconda3/envs/bactopia
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
     JAVA_LD_LIBRARY_PATH=/home/prp27/anaconda3/envs/bactopia/lib/server
                     PATH=/home/prp27/anaconda3/envs/bactopia/bin:/home/prp27/anaconda3/condabin
                          :/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/gam
                          es:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/prp27/anaconda3/envs/bactopia
            shell level : 2
       user config file : /home/prp27/.condarc
 populated config files : /home/prp27/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.10.final.0
       virtual packages : __linux=5.13.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/prp27/anaconda3/envs/bactopia  (writable)
      conda av data dir : /home/prp27/anaconda3/envs/bactopia/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/prp27/anaconda3/envs/bactopia/pkgs
                          /home/prp27/.conda/pkgs
       envs directories : /home/prp27/anaconda3/envs/bactopia/envs
                          /home/prp27/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.10 Linux/5.13.0-35-generic ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

**Comment by rpetit3** [comment]
If you have Docker or Singularity installed, you can run Bactopia with `-profile docker` or `-profile singularity`

Example
```
bactopia --accession SRX000000 -profile docker
```

I'm working on improving the documentation to better highlight using Docker and Singulairty

**Comment by plasminogene** [comment]
Thanks for your excellent work！！！

**Comment by rpetit3** [comment]
No problem, please let me know if you have any issues or feedback!
