### ISSUE TITLE
[bug] Build Datasets vfdb_full error

### ISSUE THREAD

**Issue by shigdon** [bactopia/bactopia#304]
**Description**
Cannot complete Build Datasets for Bactopia v 2.0. Seems there is duplicate record in vfdb_full raising an error. I am unsure of the best solution to fix this other than leaving out vfdb_full. Any thoughts? Thanks in advance.

**Steps to Reproduce**
```
(bactopia) [shigdon@c1hitachi20 db]$ bactopia datasets \
--ariba argannot,card,megares,plasmidfinder,resfinder,srst2_argannot,vfdb_core,vfdb_full,virulencefinder \
--skip_mlst \
--skip_prokka \
--cpus 1 \
--outdir bactopia_2.0

!!ERROR!!

2022-04-01 12:43:18:root:INFO - Setting up Ariba datasets
2022-04-01 12:43:18:root:INFO - argannot (bactopia_2.0/ariba/argannot) exists, skipping
2022-04-01 12:43:18:root:INFO - card (bactopia_2.0/ariba/card) exists, skipping
2022-04-01 12:43:18:root:INFO - megares (bactopia_2.0/ariba/megares) exists, skipping
2022-04-01 12:43:18:root:INFO - plasmidfinder (bactopia_2.0/ariba/plasmidfinder) exists, skipping
2022-04-01 12:43:18:root:INFO - resfinder (bactopia_2.0/ariba/resfinder) exists, skipping
2022-04-01 12:43:18:root:INFO - srst2_argannot (bactopia_2.0/ariba/srst2_argannot) exists, skipping
2022-04-01 12:43:18:root:INFO - vfdb_core (bactopia_2.0/ariba/vfdb_core) exists, skipping
2022-04-01 12:43:18:root:INFO - Setting up vfdb_full Ariba dataset
External command failed with exit code 1!

Command:
bash -c 'ariba prepareref -f bactopia_2.0/ariba/vfdb_full.fa -m bactopia_2.0/ariba/vfdb_full.tsv bactopia_2.0/ariba/vfdb_full'

Standard error:
Traceback (most recent call last):
  File "/ceph/home/shigdon/.conda/envs/bactopia/bin/ariba", line 312, in <module>
    args.func(args)
  File "/ceph/home/shigdon/.conda/envs/bactopia/lib/python3.9/site-packages/ariba/tasks/prepareref.py", line 34, in run
    preparer.run(options.outdir)
  File "/ceph/home/shigdon/.conda/envs/bactopia/lib/python3.9/site-packages/ariba/ref_preparer.py", line 179, in run
    self.refdata = reference_data.ReferenceData(
  File "/ceph/home/shigdon/.conda/envs/bactopia/lib/python3.9/site-packages/ariba/reference_data.py", line 34, in __init__
    self.sequences, self.metadata = ReferenceData._load_input_files_and_check_seq_names(fasta_files, metadata_tsv_files)
  File "/ceph/home/shigdon/.conda/envs/bactopia/lib/python3.9/site-packages/ariba/reference_data.py", line 136, in _load_input_files_and_check_seq_names
    all_seqs = ReferenceData._load_all_fasta_files(fasta_files)
  File "/ceph/home/shigdon/.conda/envs/bactopia/lib/python3.9/site-packages/ariba/reference_data.py", line 128, in _load_all_fasta_files
    ReferenceData._load_fasta_file(filename, seq_dict)
  File "/ceph/home/shigdon/.conda/envs/bactopia/lib/python3.9/site-packages/ariba/reference_data.py", line 119, in _load_fasta_file
    raise Error('Duplicate name "' + seq.id + '" found in file ' + filename + '. Cannot continue)')
ariba.reference_data.Error: Duplicate name "stx2B.VFG000838(gb|WP_000738068).Escherichia_coli_O157:H7_str._EDL933" found in file bactopia_2.0/ariba/vfdb_full.fa. Cannot continue)
```

**Expected Behavior**
Complete build of datasets for use with Bactopia 2.0

**Execution Environment**

- Bactopia Version: bactopia 2.0.2
- OS: Rocky Linux 8.5 (Green Obsidian)
- Environment: conda

**Additional Information**

`conda list`:

```
# packages in environment at /ceph/home/shigdon/.conda/envs/bactopia:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_sysroot_linux-64_curr_repodata_hack 3                   h5bd9786_13    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
ariba                     2.14.6           py39h67e14b5_3    bioconda
bactopia                  2.0.2                hdfd78af_0    bioconda
bcftools                  1.15                 h0ea216a_1    bioconda
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
biopython                 1.79             py39h3811e60_1    conda-forge
blast                     2.12.0               hf3cf87c_4    bioconda
bowtie2                   2.2.5            py39h7cff6ad_8    bioconda
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py39h3811e60_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.2.1             h06a4308_0
capnproto                 0.9.1                h780b84a_5    conda-forge
cd-hit                    4.8.1                h5b5514e_6    bioconda
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
coloredlogs               15.0.1           py39hf3d152e_2    conda-forge
conda                     4.11.0           py39hf3d152e_0    conda-forge
conda-package-handling    1.7.3            py39h3811e60_1    conda-forge
coreutils                 9.0                  h7f98852_0    conda-forge
cryptography              36.0.1           py39h95dcef6_0    conda-forge
curl                      7.81.0               h2574ce0_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dbus                      1.13.18              hb2f20db_0
dendropy                  4.5.2              pyh3252c3a_0    bioconda
entrez-direct             16.2                 he881be0_0    bioconda
executor                  23.2               pyhd3deb0d_0    conda-forge
expat                     2.4.6                h27087fc_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
fonttools                 4.29.1           py39h3811e60_0    conda-forge
freetype                  2.11.0               h70c0345_0
gettext                   0.21.0               hf68c758_0
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.70.2               h780b84a_4    conda-forge
glib-tools                2.70.2               h780b84a_4    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
hmmer                     3.3.2                h87f3376_2    bioconda
htslib                    1.15                 h9753748_0    bioconda
humanfriendly             10.0             py39hf3d152e_2    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
kernel-headers_linux-64   3.10.0              h4a8ded7_13    conda-forge
kiwisolver                1.3.2            py39h1a9c180_1    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libarchive                3.5.2                hccf745f_1    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libcurl                   7.81.0               h2574ce0_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20210910         h7f8727e_0
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgfortran-ng            11.2.0              h69a702a_12    conda-forge
libgfortran5              11.2.0              h5c6108e_12    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.2                h7f98852_0    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libmamba                  0.22.1               h9c208ef_0    conda-forge
libmambapy                0.22.1           py39h3216e65_0    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libsolv                   0.7.20               h4ff587b_0
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
llvm-openmp               8.0.1                hc9558a2_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.22.1           py39hfa8f2c8_0    conda-forge
mash                      2.3                  ha9a2dd8_3    bioconda
matplotlib-base           3.5.1            py39h2fa2bec_0    conda-forge
mummer                    3.23            pl5321h1b792b2_13    bioconda
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncbi-amrfinderplus        3.10.23              h6e70893_1    bioconda
ncbi-genome-download      0.3.1              pyh5e36f6f_0    bioconda
ncurses                   6.3                  h9c3ff4c_0    conda-forge
nextflow                  21.10.6              h4a94de4_0    bioconda
numpy                     1.22.2           py39h91f2184_0    conda-forge
openjdk                   11.0.13              h87a67e3_0
openjpeg                  2.4.0                hb52868f_1    conda-forge
openmp                    8.0.1                         0    conda-forge
openssl                   1.1.1m               h7f8727e_0
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-common-sense         3.75            pl5321hdfd78af_0    bioconda
perl-compress-raw-bzip2   2.101           pl5321h87f3376_1    bioconda
perl-compress-raw-zlib    2.101           pl5321h87f3376_2    bioconda
perl-encode               3.16            pl5321h779adbc_0    bioconda
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hdfd78af_0    bioconda
perl-extutils-makemaker   7.64            pl5321hd8ed1ab_0    conda-forge
perl-io-compress          2.102           pl5321h87f3376_1    bioconda
perl-io-zlib              1.11            pl5321hdfd78af_0    bioconda
perl-json                 4.05            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321h9f5acd7_5    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321hec16e2b_1    bioconda
perl-parent               0.238           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321hec16e2b_3    bioconda
perl-scalar-list-utils    1.61            pl5321hec16e2b_1    bioconda
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
pillow                    9.0.1            py39hae2aec6_2    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
property-manager          3.0                        py_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py39h3811e60_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyfastaq                  3.17.0                     py_2    bioconda
pymummer                  0.10.3                     py_2    bioconda
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pysam                     0.18.0           py39h5030a8b_2    bioconda
pysocks                   1.7.1            py39hf3d152e_4    conda-forge
python                    3.9.10          h85951f9_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1.2                h7f8727e_1
reproc                    14.2.4               h295c915_0
reproc-cpp                14.2.4               h295c915_0
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.100         py39h27cfd23_0
samtools                  1.15                 h1170115_1    bioconda
sed                       4.8                  he412f7d_0    conda-forge
setuptools                60.9.3           py39hf3d152e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
spades                    3.15.3               h95f258a_0    bioconda
sqlite                    3.37.2               hc218d9a_0
sysroot_linux-64          2.17                h4a8ded7_13    conda-forge
tbb                       2020.2               h4bd325d_4    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
unicodedata2              14.0.0           py39h3811e60_0    conda-forge
unzip                     6.0                  h7f98852_3    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
verboselogs               1.7                        py_0    conda-forge
wget                      1.20.3               ha56f1ee_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.6.3                he1b5a44_4    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

**Comment by rpetit3** [comment]
Thank you for bringing that to my attention! Unfortunately, this is not something I can fix on my end. To get this fixed, we'd need to follow up with VFDB and/or developers of Ariba. I'm not sure how long it would take to hear back from VFDB, and Ariba is not actively supported.

I think you are correct leaving `vfdb_full` is going to be the quickest and easiest solution.

**Comment by shigdon** [comment]
Thank you @rpetit3. I indeed proceeded with analyses leaving out `vfdb_full` for now and completed the WF without error.

**Comment by rpetit3** [comment]
Great! Glad you were abl;e to keep moving. I'm going to close this for now, please feel free to reopen. 

Also, if you have some time to spare, please take a moment to fill out my Bactopia survey. Your feedback will help direct the future steps of Bactopia!

https://forms.gle/PTgUxEBwCsCdbQjr7
