### ISSUE TITLE
Cannot make a datasets

### ISSUE THREAD

**Issue by lingbingzeng1985** [bactopia/bactopia#311]
Hello. I finished one project according to your advice. It is really cool. However, when I started the other project, I could not finish the datasets successfully. The Errors like this:
bactopia datasets --outdir bactopia_2.0/ --species "Escherichia coli" --include_genus --limit 100 --cpus 4
2022-05-07 14:54:32:root:INFO - Escherichia coli verified in ENA Taxonomy database
2022-05-07 14:54:32:root:INFO - Setting up Ariba datasets
2022-05-07 14:54:32:root:INFO - vfdb_core (bactopia_2.0//ariba/vfdb_core) exists, skipping
2022-05-07 14:54:32:root:INFO - card (bactopia_2.0//ariba/card) exists, skipping
2022-05-07 14:54:32:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2022-05-07 14:54:32:root:INFO - bactopia_2.0//minmer/sourmash-genbank-k21.json.gz exists, skipping
2022-05-07 14:54:32:root:INFO - bactopia_2.0//minmer/sourmash-genbank-k31.json.gz exists, skipping
2022-05-07 14:54:32:root:INFO - bactopia_2.0//minmer/sourmash-genbank-k51.json.gz exists, skipping
2022-05-07 14:54:32:root:INFO - bactopia_2.0//minmer/mash-refseq-k21.msh exists, skipping
2022-05-07 14:54:32:root:INFO - Setting up antimicrobial resistance datasets
2022-05-07 14:54:32:root:INFO - Setting up latest AMRFinder+ database
2022-05-07 15:28:49:root:INFO - AMRFinder+ database saved to bactopia_2.0//antimicrobial-resistance/amrfinderdb.tar.gz
2022-05-07 15:28:49:root:INFO - Setting up MLST datasets
2022-05-07 15:28:49:root:INFO - Escherichia coli MLST Schema (achtman) exists, skipping
2022-05-07 15:28:49:root:INFO - Escherichia coli MLST Schema (pasteur) exists, skipping
2022-05-07 15:28:49:root:INFO - Setting up custom Prokka proteins
2022-05-07 15:28:49:root:INFO - Incomplete setup, deleting bactopia_2.0//species-specific/escherichia-coli/annotation to start over
2022-05-07 15:28:49:root:INFO - Setting up custom Prokka proteins for Escherichia coli
2022-05-07 15:28:49:root:INFO - Downloading genomes (assembly level: complete)
2022-05-07 15:28:50:root:INFO - Downloading 100 genomes from a random subset of 2174 genomes.
2022-05-07 17:48:46:root:INFO - Processing 100 Genbank files
Traceback (most recent call last):
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lingbing/anaconda3/envs/bactopia/bin/bactopia-datasets.py", line 1244, in <module>
    setup_prokka(
  File "/home/lingbing/anaconda3/envs/bactopia/bin/bactopia-datasets.py", line 622, in setup_prokka
    for record in SeqIO.parse(genbank_fh, 'genbank'):
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 74, in __next__
    return next(self.records)
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 516, in parse_records
    record = self.parse(handle, do_features)
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 499, in parse
    if self.feed(handle, consumer, do_features):
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 470, in feed
    self._feed_feature_table(consumer, self.parse_features(skip=False))
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 229, in parse_features
    line = self.handle.readline()
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/gzip.py", line 313, in read1
    return self._buffer.read1(size)
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

How could I solve the problem? Thanks.

**Comment by rpetit3** [comment]
Hi @lingbingzeng1985 

Try rerunning the command with `--verbose` to get more details on where it failed.

Thank you!

**Comment by lingbingzeng1985** [comment]
Sorry to take a long time to reply. Here is the --verbose results, the errors like this:
Traceback (most recent call last):
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lingbing/anaconda3/envs/bactopia/bin/bactopia-datasets.py", line 1244, in <module>
    setup_prokka(
  File "/home/lingbing/anaconda3/envs/bactopia/bin/bactopia-datasets.py", line 622, in setup_prokka
    for record in SeqIO.parse(genbank_fh, 'genbank'):
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 74, in __next__
    return next(self.records)
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 516, in parse_records
    record = self.parse(handle, do_features)
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 499, in parse
    if self.feed(handle, consumer, do_features):
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 475, in feed
    misc_lines, sequence_string = self.parse_footer()
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 1242, in parse_footer
    line = self.handle.readline()
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/gzip.py", line 313, in read1
    return self._buffer.read1(size)
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/lingbing/anaconda3/envs/bactopia/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by lingbingzeng1985** [comment]
2022-05-11 17:44:47:executor.process:DEBUG - Executing external command: bash -c 'ncbi-genome-download bacteria -A bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/accessions.txt -l complete -o bactopia_2.0//species-specific/escherichia-coli/annotation/genomes -F genbank -r 80 -m bactopia_2.0//species-specific/escherichia-coli/annotation/ncbi-metadata.txt'
2022-05-11 17:44:47:executor.process:DEBUG - Constructing subprocess.Popen object ..
2022-05-11 17:44:47:executor.process:DEBUG - Joining synchronous process using subprocess.Popen.communicate() ..
2022-05-11 19:40:41:executor.process:DEBUG - Got return code 0 from synchronous process (bash -c 'ncbi-genome-download bacteria -A bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/accessions.txt -l complete -o bactopia_2.0//species-specific/escherichia-coli/annotation/genomes -F genbank -r 80 -m bactopia_2.0//species-specific/escherichia-coli/annotation/ncbi-metadata.txt').
2022-05-11 19:40:41:root:STDOUT - 
2022-05-11 19:40:41:root:STDERR - ERROR: Checksum mismatch for 'bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/refseq/bacteria/GCF_001886755.1/GCF_001886755.1_ASM188675v1_genomic.gbff.gz'. Expected '5975d4dccb8eb867e41e18eb542ad2ad', got 'e47545bba2258ea40d477d739b2ab884'
ERROR: Checksum mismatch for 'bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/refseq/bacteria/GCF_003956225.1/GCF_003956225.1_ASM395622v1_genomic.gbff.gz'. Expected 'c6f2d91606a708357d93fb970397ee17', got '73b3ebed771f30897a226ed0f1b056a7'
ERROR: Checksum mismatch for 'bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/refseq/bacteria/GCF_004010655.1/GCF_004010655.1_ASM401065v1_genomic.gbff.gz'. Expected '5f88ff02b3d9beab15f848c4ad991b3f', got 'd6c4686bbca819beeceb23ca61702e53'
ERROR: Checksum mismatch for 'bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/refseq/bacteria/GCF_009909485.1/GCF_009909485.1_ASM990948v1_genomic.gbff.gz'. Expected '13b9e5a3a0700b1283f7bea7e002d8ed', got '06f412d8d7168159581132071a715142'
ERROR: Checksum mismatch for 'bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/refseq/bacteria/GCF_014169195.1/GCF_014169195.1_ASM1416919v1_genomic.gbff.gz'. Expected '2f7e8610decbcb30cbf3df2465135066', got 'f37444d45e170846202b194d1de9de5b'
ERROR: Checksum mismatch for 'bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/refseq/bacteria/GCF_022493555.1/GCF_022493555.1_ASM2249355v1_genomic.gbff.gz'. Expected 'd871e927ef425c9bfd6d71e047d31155', got '0bf3e13a221f38ce01ff252cbe9a477d'
ERROR: Checksum mismatch for 'bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/refseq/bacteria/GCF_900636105.1/GCF_900636105.1_38936_F01_genomic.gbff.gz'. Expected '1d0c0a43a4f4b2172b446def4690a25e', got '2f00f83b6a36d80195a8e50631f93b4c'
ERROR: Checksum mismatch for 'bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/refseq/bacteria/GCF_000245515.1/GCF_000245515.1_ASM24551v1_genomic.gbff.gz'. Expected 'd865c34d9497837447e5bbc1c6726d66', got '5cd785fe86710a068c844429688fb723'
ERROR: Checksum mismatch for 'bactopia_2.0//species-specific/escherichia-coli/annotation/genomes/refseq/bacteria/GCF_002741175.1/GCF_002741175.1_ASM274117v1_genomic.gbff.gz'. Expected 'e2f01e3c25ce636b88157d632b00c046', got '431037712235d469acd615f298cbaf00'

2022-05-11 19:40:41:executor.process:DEBUG - Executing external command: bash -c 'find . -name "*.gbff.gz"'
2022-05-11 19:40:41:executor.process:DEBUG - Constructing subprocess.Popen object ..
2022-05-11 19:40:41:executor.process:DEBUG - Joining synchronous process using subprocess.Popen.communicate() ..
2022-05-11 19:40:41:executor.process:DEBUG - Got return code 0 from synchronous process (bash -c 'find . -name "*.gbff.gz"').
2022-05-11 19:40:41:root:STDOUT - ./genomes/refseq/bacteria/GCF_905332355.1/GCF_905332355.1_AI2831v1_genomic.gbff.gz

**Comment by lingbingzeng1985** [comment]
Hopefully, it is the problem of python. I remembered that I renewed the python edition, because I could not use the ISmapper tools.

**Comment by rpetit3** [comment]
Hi @lingbingzeng1985 

I'm going to go ahead and close this issue, please feel free to reopen if you think I can help with anything. Also, I've released [v2.1.1](https://github.com/bactopia/bactopia/releases/tag/v2.1.1).

Cheers,
Robert
