### ISSUE TITLE
Bug in  bactopia datasets update   --species "Escherichia" 

### ISSUE THREAD

**Issue by plasminogene** [bactopia/bactopia#326]
Hi,

I can not use MLST search  in  --species "Escherichia"  because of the bug in  bactopia datasets update  as following：

Thanks!

Haitao

(bactopia-dev) lh@ubuntu:~$  bactopia datasets --species "Escherichia" --include_genus  --skip_ariba  --skip_amr --keep_file 
2022-05-29 08:25:55:root:INFO - Escherichia verified in ENA Taxonomy database
2022-05-29 08:25:55:root:INFO - Skipping Ariba dataset step
2022-05-29 08:25:55:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2022-05-29 08:25:56:root:INFO - ./datasets/minmer/sourmash-genbank-k21.json.gz exists, skipping
2022-05-29 08:25:56:root:INFO - ./datasets/minmer/sourmash-genbank-k31.json.gz exists, skipping
2022-05-29 08:25:56:root:INFO - ./datasets/minmer/sourmash-genbank-k51.json.gz exists, skipping
2022-05-29 08:25:56:root:INFO - ./datasets/minmer/mash-refseq-k21.msh exists, skipping
2022-05-29 08:25:56:root:INFO - Skipping antimicrobial resistance dataset step
2022-05-29 08:25:56:root:INFO - Setting up MLST datasets
2022-05-29 08:25:56:root:ERROR - Escherichia is not available from pubMLST.org, skipping
2022-05-29 08:25:56:root:INFO - No valid MLST schemas to setup, skipping
2022-05-29 08:25:56:root:INFO - Setting up custom Prokka proteins
2022-05-29 08:25:56:root:INFO - Setting up custom Prokka proteins for Escherichia
2022-05-29 08:25:56:root:INFO - Downloading genomes (assembly level: complete)
2022-05-29 08:27:32:root:INFO - Downloading 1000 genomes from a random subset of 2207 genomes.
2022-05-29 21:15:06:root:INFO - Processing 1000 Genbank files
Traceback (most recent call last):
  File "/home/lh/anaconda3/envs/bactopia-dev/lib/python3.9/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lh/anaconda3/envs/bactopia-dev/bin/bactopia-datasets.py", line 1244, in <module>
    setup_prokka(
  File "/home/lh/anaconda3/envs/bactopia-dev/bin/bactopia-datasets.py", line 622, in setup_prokka
    for record in SeqIO.parse(genbank_fh, 'genbank'):
  File "/home/lh/anaconda3/envs/bactopia-dev/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 74, in __next__
    return next(self.records)
  File "/home/lh/anaconda3/envs/bactopia-dev/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 516, in parse_records
    record = self.parse(handle, do_features)
  File "/home/lh/anaconda3/envs/bactopia-dev/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 499, in parse
    if self.feed(handle, consumer, do_features):
  File "/home/lh/anaconda3/envs/bactopia-dev/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 470, in feed
    self._feed_feature_table(consumer, self.parse_features(skip=False))
  File "/home/lh/anaconda3/envs/bactopia-dev/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 229, in parse_features
    line = self.handle.readline()
  File "/home/lh/anaconda3/envs/bactopia-dev/lib/python3.9/gzip.py", line 313, in read1
    return self._buffer.read1(size)
  File "/home/lh/anaconda3/envs/bactopia-dev/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/lh/anaconda3/envs/bactopia-dev/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached
(bactopia-dev) lh@ubuntu:~$ ^C

**Comment by rpetit3** [comment]
Hi @plasminogene !

With the MLST you'll have to give the species name as well not just the genus. So something like "Escherichia coli" instead of just "Escherichia".

The second issue, `EOFError: Compressed file ended before the end-of-stream marker was reached` I think is a issue with an assembly on NCBI. This is not the first time I've seen this recently with Escherichia. I'll look into a way to recongnize these types of assemblies and just skip them. Will update on this soon.

For now you can try lowering the number of genomes downloaded by using `--limit 100` (or some other number.

Cheers,
Robert

**Comment by plasminogene** [comment]
I will try it ,thank your very much!

**Comment by rpetit3** [comment]
@plasminogene where you able to get things working for you?

**Comment by rpetit3** [comment]
Hi @plasminogene 

I am going to go ahead and close this issue, please feel free to reopen. Also, I've released [v2.1.1](https://github.com/bactopia/bactopia/releases/tag/v2.1.1).

Cheers,
Robert
