### ISSUE TITLE
Problems with MLST schema retrieval [bug]

### ISSUE THREAD

**Issue by mtruglio** [bactopia/bactopia#367]
**Description**
Hi, 
I am having problems downloading MLST schemas for Acinetobacter baumannii. The mlst/oxford/ariba dataset gets only partially downloaded before breaking.

**Steps to reproduce the behavior:**
```
bactopia datasets --outdir [outdir] --species "Acinetobacter baumannii"

2022-10-24 11:51:41:root:INFO - Acinetobacter baumannii verified in ENA Taxonomy database
2022-10-24 11:51:41:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2022-10-24 11:51:41:root:INFO - /mnt/DataDrive/databases/datasets//minmer/sourmash-genbank-k21.json.gz exists, skipping
2022-10-24 11:51:41:root:INFO - /mnt/DataDrive/databases/datasets//minmer/sourmash-genbank-k31.json.gz exists, skipping
2022-10-24 11:51:41:root:INFO - /mnt/DataDrive/databases/datasets//minmer/sourmash-genbank-k51.json.gz exists, skipping
2022-10-24 11:51:41:root:INFO - /mnt/DataDrive/databases/datasets//minmer/mash-refseq-k21.msh exists, skipping
2022-10-24 11:51:41:root:INFO - Setting up antimicrobial resistance datasets
2022-10-24 11:51:41:root:INFO - Setting up latest AMRFinder+ database
2022-10-24 11:51:58:root:INFO - AMRFinder+ database saved to /mnt/DataDrive/databases/datasets//antimicrobial-resistance/amrfinderdb.tar.gz
2022-10-24 11:51:58:root:INFO - Setting up MLST datasets
2022-10-24 11:51:58:root:INFO - Setting up oxford MLST schema for Acinetobacter baumannii
External command failed with exit code 1!

Command:
bash -c 'ariba pubmlstget "Acinetobacter baumannii#1" /mnt/DataDrive/databases/datasets//species-specific/acinetobacter-baumannii/mlst/oxford/ariba'

Standard error:
Traceback (most recent call last):
  File "/home/mtruglio/miniconda3/envs/bactopia/bin/ariba", line 312, in <module>
    args.func(args)
  File "/home/mtruglio/miniconda3/envs/bactopia/lib/python3.9/site-packages/ariba/tasks/pubmlstget.py", line 11, in run
    preparer.run()
  File "/home/mtruglio/miniconda3/envs/bactopia/lib/python3.9/site-packages/ariba/pubmlst_ref_preparer.py", line 81, in run
    self.profile = mlst_profile.MlstProfile(profile_file, duplicate_warnings=True)
  File "/home/mtruglio/miniconda3/envs/bactopia/lib/python3.9/site-packages/ariba/mlst_profile.py", line 15, in __init__
    self._load_input_file()
  File "/home/mtruglio/miniconda3/envs/bactopia/lib/python3.9/site-packages/ariba/mlst_profile.py", line 29, in _load_input_file
    type_tuple = tuple(int(row[x]) for x in self.genes_list)
  File "/home/mtruglio/miniconda3/envs/bactopia/lib/python3.9/site-packages/ariba/mlst_profile.py", line 29, in <genexpr>
    type_tuple = tuple(int(row[x]) for x in self.genes_list)
ValueError: invalid literal for int() with base 10: 'N'

```
**Execution Environment**

- Bactopia Version: 2.1.1
- OS: Ubuntu
- Environment: conda

**Comment by rpetit3** [comment]
So this is one we'll have to reach out to pubmlst curators on. For some reason recently `N` has been used for allele ids in some organisms. This should not be the case, and instead should be `0`.

**Comment by rpetit3** [comment]
Hi @mtruglio  I reached out to the curators, I'll let you know when I hear back

**Comment by rpetit3** [comment]
@mtruglio give this a try now, it might be fixed on the pubmlst side

**Comment by mtruglio** [comment]
Fixed! Thanks!
