### ISSUE TITLE
[bug] error in updata datasets

### ISSUE THREAD

**Issue by plasminogene** [bactopia/bactopia#382]
Hi, I found a error as follows：

(bactopia) lh@chicken:~/Desktop$ bactopia datasets --species  "Salmonella enterica"   --skip_amr
2022-12-26 13:34:20:root:INFO - Salmonella enterica verified in ENA Taxonomy database
2022-12-26 13:34:20:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2022-12-26 13:34:20:root:INFO - ./datasets/minmer/sourmash-genbank-k21.json.gz exists, skipping
2022-12-26 13:34:20:root:INFO - ./datasets/minmer/sourmash-genbank-k31.json.gz exists, skipping
2022-12-26 13:34:20:root:INFO - ./datasets/minmer/sourmash-genbank-k51.json.gz exists, skipping
2022-12-26 13:34:20:root:INFO - ./datasets/minmer/mash-refseq-k21.msh exists, skipping
2022-12-26 13:34:20:root:INFO - Skipping antimicrobial resistance dataset step
2022-12-26 13:34:20:root:INFO - Setting up MLST datasets
2022-12-26 13:34:20:root:INFO - Salmonella enterica MLST Schema (default) exists, skipping
2022-12-26 13:34:20:root:INFO - Setting up custom Prokka proteins
2022-12-26 13:34:20:root:INFO - Incomplete setup, deleting ./datasets/species-specific/salmonella-enterica/annotation to start over
2022-12-26 13:34:20:root:INFO - Setting up custom Prokka proteins for Salmonella enterica
2022-12-26 13:34:20:root:INFO - Downloading genomes (assembly level: complete)
2022-12-26 13:34:23:root:INFO - Downloading 1000 genomes from a random subset of 1198 genomes.
2022-12-26 18:37:17:root:INFO - Processing 1000 Genbank files
Traceback (most recent call last):
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/lib/python3.9/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/bin/bactopia-datasets.py", line 1091, in <module>
    setup_prokka(
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/bin/bactopia-datasets.py", line 483, in setup_prokka
    for record in SeqIO.parse(genbank_fh, 'genbank'):
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 72, in __next__
    return next(self.records)
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 516, in parse_records
    record = self.parse(handle, do_features)
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 499, in parse
    if self.feed(handle, consumer, do_features):
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 475, in feed
    misc_lines, sequence_string = self.parse_footer()
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 1242, in parse_footer
    line = self.handle.readline()
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/lib/python3.9/gzip.py", line 313, in read1
    return self._buffer.read1(size)
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/lh/anaconda3/envs/mamba/envs/bactopia/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

Thanks

Haitao

**Comment by rpetit3** [comment]
I've seen this a few times. Unfortunately this is a file with an issue on the NCBI side of things. 

One thing I can try doing is adding a quick `gzip test`, and excluding any files that fail the test.

**Comment by plasminogene** [comment]
Thank you for your kindly reply

**Comment by egenomics** [comment]
Hi, 
I get the same error. I have tried different days and different number of species but I always end up with the same error.
Is there something that can be done?
Best,
JL

`
(bactopia) jl@phoenix:~/bactopia$ echo $species
Klebsiella pneumoniae, Escherichia coli, Enterobacter cloacae, Pseudomonas aeruginosa,Citrobacter freundii,Klebsiella oxytoca,Klebsiella aerogenes,Mycobacterium tuberculosis,Enterococcus faecalis,Haemophilus influenzae,Staphylococcus aureus
(bactopia) jl@phoenix:~/bactopia$ **bactopia datasets --species "$species" --include_genus --limit 1000**
2023-03-21 16:36:19:root:INFO - Klebsiella pneumoniae verified in ENA Taxonomy database
2023-03-21 16:36:19:root:INFO - Escherichia coli verified in ENA Taxonomy database
2023-03-21 16:36:19:root:INFO - Enterobacter cloacae verified in ENA Taxonomy database
2023-03-21 16:36:20:root:INFO - Pseudomonas aeruginosa verified in ENA Taxonomy database
2023-03-21 16:36:20:root:INFO - Citrobacter freundii verified in ENA Taxonomy database
2023-03-21 16:36:20:root:INFO - Klebsiella oxytoca verified in ENA Taxonomy database
2023-03-21 16:36:20:root:INFO - Klebsiella aerogenes verified in ENA Taxonomy database
2023-03-21 16:36:21:root:INFO - Mycobacterium tuberculosis verified in ENA Taxonomy database
2023-03-21 16:36:21:root:INFO - Enterococcus faecalis verified in ENA Taxonomy database
2023-03-21 16:36:21:root:INFO - Haemophilus influenzae verified in ENA Taxonomy database
2023-03-21 16:36:21:root:INFO - Staphylococcus aureus verified in ENA Taxonomy database
2023-03-21 16:36:21:root:INFO - Setting up pre-computed Genbank/Refseq minmer datasets
2023-03-21 16:36:21:root:INFO - ./datasets/minmer/sourmash-genbank-k21.json.gz exists, skipping
2023-03-21 16:36:21:root:INFO - ./datasets/minmer/sourmash-genbank-k31.json.gz exists, skipping
2023-03-21 16:36:21:root:INFO - ./datasets/minmer/sourmash-genbank-k51.json.gz exists, skipping
2023-03-21 16:36:21:root:INFO - ./datasets/minmer/mash-refseq-k21.msh exists, skipping
2023-03-21 16:36:21:root:INFO - Setting up antimicrobial resistance datasets
2023-03-21 16:36:21:root:INFO - Setting up latest AMRFinder+ database
2023-03-21 16:36:38:root:INFO - AMRFinder+ database saved to ./datasets/antimicrobial-resistance/amrfinderdb.tar.gz
2023-03-21 16:36:38:root:INFO - Setting up MLST datasets
2023-03-21 16:36:38:root:INFO - Setting up default MLST schema for Klebsiella pneumoniae
2023-03-21 16:36:42:root:INFO - Setting up achtman MLST schema for Escherichia coli
2023-03-21 16:36:49:root:INFO - Setting up pasteur MLST schema for Escherichia coli
2023-03-21 16:36:53:root:INFO - Setting up default MLST schema for Enterobacter cloacae
2023-03-21 16:36:57:root:INFO - Pseudomonas aeruginosa MLST Schema (default) exists, skipping
2023-03-21 16:36:57:root:INFO - Setting up default MLST schema for Citrobacter freundii
2023-03-21 16:37:01:root:INFO - Setting up default MLST schema for Klebsiella oxytoca
2023-03-21 16:37:06:root:INFO - Setting up default MLST schema for Klebsiella aerogenes
2023-03-21 16:37:09:root:INFO - Mycobacterium tuberculosis MLST Schema (default) exists, skipping
2023-03-21 16:37:09:root:INFO - Enterococcus faecalis MLST Schema (default) exists, skipping
2023-03-21 16:37:09:root:INFO - Haemophilus influenzae MLST Schema (default) exists, skipping
2023-03-21 16:37:09:root:INFO - Staphylococcus aureus MLST Schema (default) exists, skipping
2023-03-21 16:37:09:root:INFO - Setting up custom Prokka proteins
2023-03-21 16:37:09:root:INFO - Setting up custom Prokka proteins for Klebsiella pneumoniae
2023-03-21 16:37:09:root:INFO - Downloading genomes (assembly level: complete)
2023-03-21 16:37:15:root:INFO - Downloading 1000 genomes from a random subset of 1819 genomes.
2023-03-21 17:26:50:root:INFO - Processing 1000 Genbank files
2023-03-21 17:38:53:root:INFO - Median genome size: 5669225 (n=814)
2023-03-21 17:38:53:root:INFO - Running CD-HIT on 5318032 proteins
2023-03-21 17:48:52:root:INFO - Setting up custom Prokka proteins for escherichia coli
2023-03-21 17:48:52:root:INFO - Downloading genomes (assembly level: complete)
2023-03-21 17:48:54:root:INFO - Downloading 1000 genomes from a random subset of 2646 genomes.
2023-03-21 18:20:24:root:INFO - Processing 1000 Genbank files
2023-03-21 18:31:36:root:INFO - Median genome size: 5137004 (n=956)
2023-03-21 18:31:36:root:INFO - Running CD-HIT on 4684225 proteins
2023-03-21 18:39:31:root:INFO - Setting up custom Prokka proteins for enterobacter cloacae
2023-03-21 18:39:31:root:INFO - Downloading genomes (assembly level: complete)
2023-03-21 18:39:33:root:INFO - There are less available genomes than the given limit (1000), downloading all.
2023-03-21 18:54:00:root:INFO - Processing 473 Genbank files
2023-03-21 18:59:04:root:INFO - Median genome size: 5102095 (n=68)
2023-03-21 18:59:04:root:INFO - Running CD-HIT on 2205187 proteins
2023-03-21 19:03:51:root:INFO - Setting up custom Prokka proteins for pseudomonas aeruginosa
2023-03-21 19:03:51:root:INFO - Downloading genomes (assembly level: complete)
2023-03-21 19:03:53:root:INFO - Downloading 1000 genomes from a random subset of 1334 genomes.
2023-03-21 19:34:11:root:INFO - Processing 1000 Genbank files
Traceback (most recent call last):
  File "/home/jl/miniconda3/envs/bactopia/lib/python3.9/site-packages/Bio/File.py", line 72, in as_handle
    with open(handleish, mode, **kwargs) as fp:
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jl/miniconda3/envs/bactopia/bin/bactopia-datasets.py", line 1091, in <module>
    setup_prokka(
  File "/home/jl/miniconda3/envs/bactopia/bin/bactopia-datasets.py", line 483, in setup_prokka
    for record in SeqIO.parse(genbank_fh, 'genbank'):
  File "/home/jl/miniconda3/envs/bactopia/lib/python3.9/site-packages/Bio/SeqIO/Interfaces.py", line 72, in __next__
    return next(self.records)
  File "/home/jl/miniconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 516, in parse_records
    record = self.parse(handle, do_features)
  File "/home/jl/miniconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 499, in parse
    if self.feed(handle, consumer, do_features):
  File "/home/jl/miniconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 470, in feed
    self._feed_feature_table(consumer, self.parse_features(skip=False))
  File "/home/jl/miniconda3/envs/bactopia/lib/python3.9/site-packages/Bio/GenBank/Scanner.py", line 229, in parse_features
    line = self.handle.readline()
  File "/home/jl/miniconda3/envs/bactopia/lib/python3.9/gzip.py", line 313, in read1
    return self._buffer.read1(size)
  File "/home/jl/miniconda3/envs/bactopia/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/jl/miniconda3/envs/bactopia/lib/python3.9/gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "
**EOFError: Compressed file ended before the end-of-stream marker was reached**
`

**Comment by rpetit3** [comment]
Hi all! 

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
