### ISSUE TITLE
How to just download everything in the beginning?

### ISSUE THREAD

**Issue by lskatz** [bactopia/bactopia#387]
Hi, how do I just make sure all the conda envs are ready to go when I start off?  I installed to a custom directory with conda:

```
$ mamba create -p bactopia -c conda-forge -c bioconda bactopia
```

And then I tried out the python script:
```
$ conda activate ./bactopia
(bactopia) [gzu2@monolith3 envs]$ bactopia-download.py --build_all bactopia
Traceback (most recent call last):
  File "/scicomp/groups/OID/NCEZID/DFWED/EDLB/envs/bactopia/bin/bactopia-download.py", line 535, in <module>
    workflow_modules = parse_workflows(bactopia_path, include_merlin=include_merlin, build_all=args.build_all)
  File "/scicomp/groups/OID/NCEZID/DFWED/EDLB/envs/bactopia/bin/bactopia-download.py", line 150, in parse_workflows
    nf_config, stderr = execute(f'nextflow config -flat {bactopia_path}/main.nf', capture=True)
TypeError: cannot unpack non-iterable NoneType object
```

Should this be added into the documentation?

**Comment by rpetit3** [comment]
For this you will want to use `bactopia download` instead of `bactopia-download.py`. It should bring the needed 

As you go through this, please feel free to add any feedback here!
