### ISSUE TITLE
[bug] ncbi-genome-download

### ISSUE THREAD

**Issue by steven-bioinfo** [bactopia/bactopia#422]
Hello,

**Description**
I have an error in bactopia dataset when i specify a species when this script download assembly_accession.

**Steps to Reproduce**
```
bactopia datasets --include_genus --outdir /data/tools/bactopia/datasets/ --cpus 4 --skip_amr --species "Lactococcus cremoris"
```

**Error**
```
2023-06-22 13:41:42:root:INFO - Setting up custom Prokka proteins for Lactococcus cremoris
2023-06-22 13:41:42:root:INFO - Downloading genomes (assembly level: complete)

External command failed with exit code 1!

Command:
bash -c 'ncbi-genome-download bacteria -g "Lactococcus" -l complete -F genbank -r 80 --dry-run'

Standard error:
Traceback (most recent call last):
  File "/nfs/apps/modules/bioinfo/bactopia/bactopia_2.0.3/bin/ncbi-genome-download", line 10, in <module>
    sys.exit(main())
  File "/nfs/apps/modules/bioinfo/bactopia/bactopia_2.0.3/lib/python3.9/site-packages/ncbi_genome_download/__main__.py", line 26, in main
    ret = args_download(args)
  File "/nfs/apps/modules/bioinfo/bactopia/bactopia_2.0.3/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 178, in args_download
    return config_download(config)
  File "/nfs/apps/modules/bioinfo/bactopia/bactopia_2.0.3/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 197, in config_download
    download_candidates = select_candidates(config)
  File "/nfs/apps/modules/bioinfo/bactopia/bactopia_2.0.3/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 308, in select_candidates
    for entry in filter_entries(entries, config):
  File "/nfs/apps/modules/bioinfo/bactopia/bactopia_2.0.3/lib/python3.9/site-packages/ncbi_genome_download/core.py", line 354, in filter_entries
    if not config.is_compatible_assembly_accession(entry['assembly_accession']):
KeyError: 'assembly_accession'
```

**Execution Environment**

- Bactopia Version: 2.0.3 and 2.2.0
- OS: rockylinux 8
- Environment: conda

**Additional Information**
I try with others species and I have the same error.

**Comment by rpetit3** [comment]
Hi @steven-bioinfo 

This looks related to an open issue here: https://github.com/kblin/ncbi-genome-download/issues/209

I've submitted a pull request to Bioconda (https://github.com/bioconda/bioconda-recipes/pull/41640) to incorporate a solution described in https://github.com/kblin/ncbi-genome-download/issues/210

I can then incorporate that fix in my dev build of Bactopia. Otherwise, you can manually edit your `/nfs/apps/modules/bioinfo/bactopia/bactopia_2.0.3/lib/python3.9/site-packages/ncbi_genome_download/summary.py` file to include the changes described here: https://github.com/kblin/ncbi-genome-download/issues/210 (patch file here: https://github.com/chasemc/ncbi-genome-download/commit/4c5c24e27aa8123c7995890046b17b815da3571b.diff)

I'll keep you posted on my end. Let me know if this helps!

Robert

**Comment by steven-bioinfo** [comment]
Hello,

thanks for the patch, I modify the file  and the bactopia datasets tasks are completed.

The ncbi_genome_download packages are also used in the CALL_VARIANTS step.  The same changes need to be done in the conda/envs/call_variants-2.2.x/lib/python3.7/site-packages/ncbi_genome_download/summary.py

Regards,

Steven

**Comment by rpetit3** [comment]
Thanks @steven-bioinfo ! This is now fixed in my latest dev build https://github.com/bactopia/bactopia/issues/394 

Feel free to give it a try, feedback much appreciated
