### ISSUE TITLE
Error running minmer sketch using -profile singularity

### ISSUE THREAD

**Issue by azmigueldario** [bactopia/bactopia#427]
I am running a pilot with a couple of samples. It worked in our small testing cluster but I had to adapt it for the real HPC and it's not working. 

There is no problem with the sample sheet, for the `minmer_sketch` tried pulling again the singularity image to no avail. 

```
Estimated genome size: 3.95862e+07
Estimated coverage:    17.5957
Writing to SRX1154245_SRR2158266-k21.msh...
Estimated genome size: 4.12742e+07
Estimated coverage:    15.153
Writing to SRX1154245_SRR2158266-k31.msh...
Traceback (most recent call last):
  File "/home/mdprieto/.local/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/mdprieto/.local/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/mdprieto/.local/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libflexiblas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/bactopia-minmers/bin/sourmash", line 7, in <module>
    from sourmash.__main__ import main
  File "/opt/conda/envs/bactopia-minmers/lib/python3.10/site-packages/sourmash/__init__.py", line 50, in <module>
    from .minhash import MinHash, get_minhash_default_seed, get_minhash_max_hash
  File "/opt/conda/envs/bactopia-minmers/lib/python3.10/site-packages/sourmash/minhash.py", line 9, in <module>
    from .distance_utils import jaccard_to_distance, containment_to_distance, set_size_chernoff
  File "/opt/conda/envs/bactopia-minmers/lib/python3.10/site-packages/sourmash/distance_utils.py", line 7, in <module>
    from scipy.optimize import brentq
  File "/opt/conda/envs/bactopia-minmers/lib/python3.10/site-packages/scipy/__init__.py", line 73, in <module>
    from numpy import show_config as show_numpy_config
  File "/home/mdprieto/.local/lib/python3.10/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/mdprieto/.local/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/opt/conda/envs/bactopia-minmers/bin/python"
  * The NumPy version is: "1.23.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libflexiblas.so.3: cannot open shared object file: No such file or directory
```

**Comment by rpetit3** [comment]
Hi @azmigueldario, 

Let's get this figured out so we can get you going. Could you post the command you used? Also would you be interested if switching to my dev build for v3 (will be released soon), details are here: https://github.com/bactopia/bactopia/issues/394

Thanks!
Robert

**Comment by azmigueldario** [comment]
I'll try your dev build just in case. And thank you very much for your quick reply @rpetit3 

The command I used was:
```
# load modules
module load nextflow apptainer scipy-stack/2023a

# define environment variables
SAMPLESHEET="/project/6056895/mdprieto/giardia_mlst_2023/processed_data/pilot_bactopia_samplesheet.csv"
SINGULARITY_LOCAL_CACHE="/project/6007413/cidgoh_share/singularity_imgs"

######################################################

# bactopia v2.2.0
nextflow run bactopia/main.nf \
    -profile singularity \
    -resume \
    --samples $SAMPLESHEET \
    --outdir results/bactopia_giardia \
    --shovill_assembler spades \
    --skip_amr \
    --singularity_cache $SINGULARITY_LOCAL_CACHE
```

**Comment by rpetit3** [comment]
Thank you for sharing this.

What is the job schedular for this cluster (slurm, sge, pbs, etc...)

**Comment by azmigueldario** [comment]
We have **slurm**, but I meant to run it as a local executable inside a job as the scheduler is taking forever.

**Comment by azmigueldario** [comment]
I am running a new job with the `dev` branch to see if it works. I'll get back to you with the results robert, I will also submit one with `-profile singularity,slurm` just in case. Thanks a lot

**Comment by rpetit3** [comment]
If you choose the `-profile slurm` we'll probably need to add a few options, and skip the inside job.

The `-profile slurm` will allow Nextflow to communicate with the scheduler directly and submit each task as a slurm job (which I think you are wanting to avoid due to the potential delays)

**Comment by azmigueldario** [comment]
Hello @rpetit3 , thanks for the help. 

I figured it out; apparently nextflow was trying to use the Python interpreter and modules from my HPC environment. The issue was my preconfigured binding of `/opt,/etc` and the design of the cluster. 

I solved it by adding the following flag to the `docker.config` for that part of the workflow, as `singularity.config` inherits from it. It's probably highly specific to our HPC but I post it in case someone finds a similar issue. 

```
# in docker.config
  withLabel: 'minmer_sketch|minmer_query' {
      container = "${docker_repo}/minmers:${manifest.version}"
      singularity.runOptions = "-c --bind /project,/scratch"
      }
```
