### ISSUE TITLE
Failing perl due to locale (conda) [bug]

### ISSUE THREAD

**Issue by iferres** [bactopia/bactopia#429]
**Description**
Apparently many programs are grabbing their versions with locale warnings included, making `BACTOPIA:CUSTOM_DUMPSOFTWAREVERSIONS` to fail.

**Steps to Reproduce**
Here's the error:
```
Traceback (most recent call last):
  File "/mnt/data/ezbiome_sequencing/ezbiome_seq-data-kinzbio_48-isolates_2023-08-16_1526/species/staphylococcus_aureus/work/f0/04f32a088f23135eb1b0d32464033d/.command.sh", line 52, in <module>
    workflow_versions = yaml.load(f, Loader=yaml.BaseLoader) | module_versions
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
           ^^^^^^^^^^^^^^^^^^
  File "/home/iferres/miniconda3/envs/bactopia/share/bactopia-2.2.x/conda/envs/bioconda--multiqc-1.11/lib/python3.11/site-packages/yaml/scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "versions.yml", line 2, column 21
```
And here's the `versions.yml` file.
```
$cat versions.yml

"BACTOPIA:ASSEMBLE_GENOME":
    any2fasta:  perl: warning: Setting locale failed. perl: warning: Please check that your locale settings: LANGUAGE = (unset), LC_ALL = (unset), LC_ADDRESS = "es_UY.UTF-8", LC_NAME = "es_UY.UTF-8", LC_MONETARY = "es_UY.UTF-8", LC_PAPER = "es_UY.UTF-8", LC_TERMINAL = "iTerm2", LC_IDENTIFICATION = "es_UY.UTF-8", LC_TELEPHONE = "es_UY.UTF-8", LC_MEASUREMENT = "es_UY.UTF-8", LC_CTYPE = "UTF-8", LC_TIME = "es_UY.UTF-8", LC_NUMERIC = "es_UY.UTF-8", LANG = "en_US.UTF-8" are supported and installed on your system. perl: warning: Falling back to a fallback locale ("en_US.UTF-8"). 0.4.2
    assembly-scan: 0.4.1
    bwa: 0.7.17-r1188
    flash: 1.2.11
    flye: 2.9.1-b1780
    makeblastdb: 2.13.0+
    medaka: 1.5.0
    megahit: 1.2.9
    miniasm: 0.3-r179
    minimap2: 2.24-r1122
    nanoq: 0.9.0
    pigz: 2.6
    pilon: 1.24
    racon: 1.5.0
    rasusa: 0.7.0
    raven: 1.8.1
    samclip: perl: warning: Setting locale failed. perl: warning: Please check that your locale settings: LANGUAGE = (unset), LC_ALL = (unset), LC_ADDRESS = "es_UY.UTF-8", LC_NAME = "es_UY.UTF-8", LC_MONETARY = "es_UY.UTF-8", LC_PAPER = "es_UY.UTF-8", LC_TERMINAL = "iTerm2", LC_IDENTIFICATION = "es_UY.UTF-8", LC_TELEPHONE = "es_UY.UTF-8", LC_MEASUREMENT = "es_UY.UTF-8", LC_CTYPE = "UTF-8", LC_TIME = "es_UY.UTF-8", LC_NUMERIC = "es_UY.UTF-8", LANG = "en_US.UTF-8" are supported and installed on your system. perl: warning: Falling back to a fallback locale ("en_US.UTF-8"). 0.4.0
    samtools: 1.15
    shovill: perl: warning: Setting locale failed. perl: warning: Please check that your locale settings: LANGUAGE = (unset), LC_ALL = (unset), LC_ADDRESS = "es_UY.UTF-8", LC_NAME = "es_UY.UTF-8", LC_MONETARY = "es_UY.UTF-8", LC_PAPER = "es_UY.UTF-8", LC_TERMINAL = "iTerm2", LC_IDENTIFICATION = "es_UY.UTF-8", LC_TELEPHONE = "es_UY.UTF-8", LC_MEASUREMENT = "es_UY.UTF-8", LC_CTYPE = "UTF-8", LC_TIME = "es_UY.UTF-8", LC_NUMERIC = "es_UY.UTF-8", LANG = "en_US.UTF-8" are supported and installed on your system. perl: warning: Falling back to a fallback locale ("en_US.UTF-8"). 1.1.0
    shovill-se: perl: warning: Setting locale failed. perl: warning: Please check that your locale settings: LANGUAGE = (unset), LC_ALL = (unset), LC_ADDRESS = "es_UY.UTF-8", LC_NAME = "es_UY.UTF-8", LC_MONETARY = "es_UY.UTF-8", LC_PAPER = "es_UY.UTF-8", LC_TERMINAL = "iTerm2", LC_IDENTIFICATION = "es_UY.UTF-8", LC_TELEPHONE = "es_UY.UTF-8", LC_MEASUREMENT = "es_UY.UTF-8", LC_CTYPE = "UTF-8", LC_TIME = "es_UY.UTF-8", LC_NUMERIC = "es_UY.UTF-8", LANG = "en_US.UTF-8" are supported and installed on your system. perl: warning: Falling back to a fallback locale ("en_US.UTF-8"). 1.1.0
    skesa: 2.4.0
    spades.py: 3.15.5
    velvetg: 1.2.10
    velveth: 1.2.10
    unicycler: 0.5.0
"BACTOPIA:CALL_VARIANTS":
    bedtools: 2.30.0
    mash: 2.3
    ncbi-genome-download: 0.3.1
    pigz: 2.6
    snippy: perl: warning: Setting locale failed. perl: warning: Please check that your locale settings: LANGUAGE = (unset), LC_ALL = (unset), LC_ADDRESS = "es_UY.UTF-8", LC_NAME = "es_UY.UTF-8", LC_MONETARY = "es_UY.UTF-8", LC_PAPER = "es_UY.UTF-8", LC_TERMINAL = "iTerm2", LC_IDENTIFICATION = "es_UY.UTF-8", LC_TELEPHONE = "es_UY.UTF-8", LC_MEASUREMENT = "es_UY.UTF-8", LC_CTYPE = "UTF-8", LC_TIME = "es_UY.UTF-8", LC_NUMERIC = "es_UY.UTF-8", LANG = "en_US.UTF-8" are supported and installed on your system. perl: warning: Falling back to a fallback locale ("en_US.UTF-8"). 4.6.0
    vcf-annotator: 0.7
"BACTOPIA:GATHER_SAMPLES":
    art: 2.5.8
    fastq-dl: 1.1.1
    fastq-scan: 1.0.1
    mash: 2.3
    ncbi-genome-download: 0.3.1
    pigz: 2.6
"BACTOPIA:QC_READS":
    bbduk: 39.01
    fastp: 0.23.2
    fastqc: 0.11.9
    fastq-scan: 1.0.1
    lighter: 1.1.2
    nanoplot: 1.40.2
    nanoq: 0.9.0
    pigz: 2.6
    porechop: 0.2.4
    rasusa: 0.7.0
"BACTOPIA:MINMER_QUERY":
    mash: 2.3
    sourmash: 4.5.0
"BACTOPIA:MINMER_SKETCH":
    mash: 2.3
    mccortex: 0.0.3-610-g400c0e3
    sourmash: 4.5.0
"BACTOPIA:ASSEMBLY_QC":
    quast: 5.2.0
"BACTOPIA:SEQUENCE_TYPE":
    blastn: 2.13.0+
"BACTOPIA:ANNOTATE_GENOME":
    prokka:  perl: warning: Setting locale failed. perl: warning: Please check that your locale settings: LANGUAGE = (unset), LC_ALL = (unset), LC_ADDRESS = "es_UY.UTF-8", LC_NAME = "es_UY.UTF-8", LC_MONETARY = "es_UY.UTF-8", LC_PAPER = "es_UY.UTF-8", LC_TERMINAL = "iTerm2", LC_IDENTIFICATION = "es_UY.UTF-8", LC_TELEPHONE = "es_UY.UTF-8", LC_MEASUREMENT = "es_UY.UTF-8", LC_CTYPE = "UTF-8", LC_TIME = "es_UY.UTF-8", LC_NUMERIC = "es_UY.UTF-8", LANG = "en_US.UTF-8" are supported and installed on your system. perl: warning: Falling back to a fallback locale ("en_US.UTF-8"). 1.14.6
"BACTOPIA:ANTIMICROBIAL_RESISTANCE":
    amrfinder:  3.10.45
```

**Execution Environment**

- Bactopia Version: bactopia 2.2.0
- OS: Ubuntu 20.04
- Environment: conda

Thank you for this awesome tool BTW!

**Comment by rpetit3** [comment]
Hi @iferres, 

I'll get this fixed, thank you for reporting!

**Comment by rpetit3** [comment]
I'm sure there might be some more that pop up but the ones above should be fixed in v3 : https://github.com/bactopia/bactopia/commit/a64b21576995aaa0b9cc055f434f849afa254597

**Comment by rpetit3** [comment]
Hi @iferres,

I'm happy to report I have [released version 3 of Bactopia](https://github.com/bactopia/bactopia/releases/tag/v3.0.0). With this release, your issue should now be taken care of. 

If not please feel free to reopen this issue or create a new one.

Thanks for using Bactopia!
Robert
