### ISSUE TITLE
[bug]  Bactopia running LisSero on Enterococci?

### ISSUE THREAD

**Issue by incoherentian** [bactopia/bactopia#437]
**Description**
Bactopia running LisSero on Enterococci.
Ultimately ends run with:

```
Command exit status:
  1
```
due to
```
[c.medib@cl1(hawk) 7d09be3242d017b01475b293b27091]$ cat .command.log
WARNING: Skipping mount /var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
2023-09-02 03:45:51.550 | INFO     | lissero.scripts.Serotype:_load_log:285 - Successfully loaded DB log!
2023-09-02 03:45:51.551 | INFO     | lissero.scripts.Serotype:check_db:260 - DB was created on 2020-06-04T11:57:55.145347
2023-09-02 03:45:51.551 | INFO     | lissero.scripts.Serotype:check_db:261 - DB is ready for use.
2023-09-02 03:45:51.552 | INFO     | lissero.scripts.Sample:get_serotype:29 - Serotyping: [redacted]_.fna
2023-09-02 03:45:51.552 | INFO     | lissero.scripts.Blast:run:52 - Blastn is running: /usr/local/bin/blastn -db /usr/local/lib/python3.9/site-packages/lissero/db/lissero -ungapped -culling_limit 1 -outfmt 6 qaccver saccver length slen pident -dust no -query /scratch/c.medib/sh_bactopia/work/e5/7d09be3242d017b01475b293b27091/[redacted]_.fna
Traceback (most recent call last):
  File "/usr/local/bin/lissero", line 10, in <module>
    sys.exit(run_lissero())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/lissero/run_lissero.py", line 119, in run_lissero
    samples.run_typing()
  File "/usr/local/lib/python3.9/site-packages/lissero/scripts/Sample.py", line 82, in run_typing
    self._run_typing("serotype")
  File "/usr/local/lib/python3.9/site-packages/lissero/scripts/Sample.py", line 75, in _run_typing
    f.get_serotype()
  File "/usr/local/lib/python3.9/site-packages/lissero/scripts/Sample.py", line 30, in get_serotype
    self.serotype.generate_type(self.filename)
  File "/usr/local/lib/python3.9/site-packages/lissero/scripts/Serotype.py", line 222, in generate_type
    self._blast_parse()
  File "/usr/local/lib/python3.9/site-packages/lissero/scripts/Serotype.py", line 202, in _blast_parse
    (qaccver, saccver, length, slen, pident) = b.split("\t")
ValueError: not enough values to unpack (expected 5, got 1)
[c.medib@cl1(hawk) 7d09be3242d017b01475b293b27091]$
```

**Steps to Reproduce**
Run bactopia with Merlin on an _E. faecalis_. 

**Expected Behavior**
LisSero does not run on Enterococci. Bactopia finishes run.

**Execution Environment**
Bactopia-dev conda env set up with mamba, SLURM executor(HPC using RHEL fwiw), Singularity-SE container management. Using only 40-core (x86_64, HT-disabled) nodes currently. 180GB RAM, GPU-free.

**Additional Information**
May be occuring due to order being Lactobacillales?

Incidental to bug (because I don't envision wanting Merlin to pull LisSero anyway): Is it possible to tell Merlin to simply not run certain Merlinabled workflows?

**Comment by rpetit3** [comment]
This is a fun one @incoherentian. Haha as you've found out LisSero, exits with non-0 when the input sample is _not_ listeria. I had to build in a few checks to avoid this scenario. You got past it! 

Can you by chance dig up the results from the `MERLINDIST`? I'm curious what the mash distance to a Listeria genome was. I'm thinking the distance checks for Listeria might need to be more stringent.

**Comment by rpetit3** [comment]
@incoherentian been thinking about this one, I'm thinking I will remove LisSero from merlin. Given Merlin is just an attempt to run additional tools for you, I think it should only support tools that allow a negative result. Tools like LisSero which fail dramatically on negative results (pneumoCAT is the only other one I can think of), should be run separately when the user has a better idea about the sample.

**Comment by incoherentian** [comment]
That's fine! Actually what I would have done for the local env, had I the confidence to tinker with such a massive and tightly interconnected nf script as yours.

Thanks as always for your time taken parsing logs etc. when determining best path forward :)

**Comment by rpetit3** [comment]
I think it might just be removing "listeria" from this line: https://github.com/bactopia/bactopia/blob/master/modules/nf-core/mash/dist/main.nf#L111

If you want to play around.

**Comment by incoherentian** [comment]
Victory!

<details>

<summary>
job execution summary
</summary>

```
executor >  slurm (846)
[skipped  ] process > BACTOPIA:DATASETS              [100%] 1 of 1, stored: 1 ✔
[cb/0fa7ed] process > BACTOPIA:GATHER:GATHER_MODU... [100%] 77 of 77 ✔
[09/41baea] process > BACTOPIA:GATHER:CSVTK_CONCA... [100%] 1 of 1 ✔
[8b/88a93f] process > BACTOPIA:QC:QC_MODULE (AZTE... [100%] 77 of 77 ✔
[62/5e0c6a] process > BACTOPIA:ASSEMBLER:ASSEMBLE... [100%] 77 of 77 ✔
[21/73d2d4] process > BACTOPIA:ASSEMBLER:CSVTK_CO... [100%] 1 of 1 ✔
[c9/cbe733] process > BACTOPIA:SKETCHER:SKETCHER_... [100%] 76 of 76 ✔
[8b/b387ce] process > BACTOPIA:ANNOTATOR:PROKKA_M... [100%] 76 of 76 ✔
[48/944a3e] process > BACTOPIA:AMRFINDERPLUS:AMRF... [100%] 76 of 76 ✔
[d6/f15866] process > BACTOPIA:AMRFINDERPLUS:GENE... [100%] 1 of 1 ✔
[1e/668d13] process > BACTOPIA:AMRFINDERPLUS:PROT... [100%] 1 of 1 ✔
[52/44e32f] process > BACTOPIA:MLST:MLST_MODULE (... [100%] 76 of 76 ✔
[3f/edd43a] process > BACTOPIA:MLST:CSVTK_CONCAT ... [100%] 1 of 1 ✔
[c9/8fc49e] process > BACTOPIA:MERLIN:MERLINDIST:... [100%] 76 of 76 ✔
[f9/8a3428] process > BACTOPIA:MERLIN:ECTYPER:ECT... [100%] 4 of 4 ✔
[af/8ddc94] process > BACTOPIA:MERLIN:ECTYPER:CSV... [100%] 1 of 1 ✔
[9c/6ed980] process > BACTOPIA:MERLIN:SHIGATYPER:... [100%] 4 of 4 ✔
[64/bde9a0] process > BACTOPIA:MERLIN:SHIGATYPER:... [100%] 1 of 1 ✔
[76/42fc8b] process > BACTOPIA:MERLIN:SHIGEIFINDE... [100%] 4 of 4 ✔
[d6/86462c] process > BACTOPIA:MERLIN:SHIGEIFINDE... [100%] 1 of 1 ✔
[ac/88e78a] process > BACTOPIA:MERLIN:STECFINDER:... [100%] 4 of 4 ✔
[55/5b2dff] process > BACTOPIA:MERLIN:STECFINDER:... [100%] 1 of 1 ✔
[-        ] process > BACTOPIA:MERLIN:HICAP:HICAP... -
[-        ] process > BACTOPIA:MERLIN:HICAP:CSVTK... -
[-        ] process > BACTOPIA:MERLIN:HPSUISSERO:... -
[-        ] process > BACTOPIA:MERLIN:HPSUISSERO:... -
[36/0de740] process > BACTOPIA:MERLIN:KLEBORATE:K... [100%] 4 of 4 ✔
[49/2fe09c] process > BACTOPIA:MERLIN:KLEBORATE:C... [100%] 1 of 1 ✔
[-        ] process > BACTOPIA:MERLIN:LEGSTA:LEGS... -
[-        ] process > BACTOPIA:MERLIN:LEGSTA:CSVT... -
[-        ] process > BACTOPIA:MERLIN:LISSERO:LIS... -
[-        ] process > BACTOPIA:MERLIN:LISSERO:CSV... -
[-        ] process > BACTOPIA:MERLIN:TBPROFILER:... -
[-        ] process > BACTOPIA:MERLIN:MENINGOTYPE... -
[-        ] process > BACTOPIA:MERLIN:MENINGOTYPE... -
[-        ] process > BACTOPIA:MERLIN:NGMASTER:NG... -
[-        ] process > BACTOPIA:MERLIN:NGMASTER:CS... -
[-        ] process > BACTOPIA:MERLIN:PASTY:PASTY... -
[-        ] process > BACTOPIA:MERLIN:PASTY:CSVTK... -
[-        ] process > BACTOPIA:MERLIN:GENOTYPHI:M... -
[-        ] process > BACTOPIA:MERLIN:GENOTYPHI:G... -
[-        ] process > BACTOPIA:MERLIN:GENOTYPHI:C... -
[-        ] process > BACTOPIA:MERLIN:SEQSERO2:SE... -
[-        ] process > BACTOPIA:MERLIN:SEQSERO2:CS... -
[-        ] process > BACTOPIA:MERLIN:SISTR:SISTR... -
[-        ] process > BACTOPIA:MERLIN:SISTR:CSVTK... -
[1c/fe0c25] process > BACTOPIA:MERLIN:STAPHTYPER:... [100%] 67 of 67 ✔
[72/e6528b] process > BACTOPIA:MERLIN:STAPHTYPER:... [100%] 67 of 67 ✔
[32/0f193e] process > BACTOPIA:MERLIN:STAPHTYPER:... [100%] 67 of 67 ✔
[16/3dc8a9] process > BACTOPIA:MERLIN:STAPHTYPER:... [100%] 1 of 1 ✔
[85/1321dd] process > BACTOPIA:MERLIN:STAPHTYPER:... [100%] 1 of 1 ✔
[ae/9c058d] process > BACTOPIA:MERLIN:STAPHTYPER:... [100%] 1 of 1 ✔
[-        ] process > BACTOPIA:MERLIN:EMMTYPER:EM... -
[-        ] process > BACTOPIA:MERLIN:EMMTYPER:CS... -
[-        ] process > BACTOPIA:MERLIN:PBPTYPER:PB... -
[-        ] process > BACTOPIA:MERLIN:PBPTYPER:CS... -
[-        ] process > BACTOPIA:MERLIN:PNEUMOCAT:P... -
[-        ] process > BACTOPIA:MERLIN:SEROBA:SERO... -
[-        ] process > BACTOPIA:MERLIN:SEROBA:CSVT... -
[-        ] process > BACTOPIA:MERLIN:SSUISSERO:S... -
[-        ] process > BACTOPIA:MERLIN:SSUISSERO:C... -
[53/ee8194] process > BACTOPIA:DUMPSOFTWAREVERSIO... [100%] 1 of 1 ✔

    Bactopia Execution Summary
    ---------------------------
    Bactopia Version : 3.0.0
    Nextflow Version : 23.04.1
```

</details>

**Comment by incoherentian** [comment]
Synopsis for anyone else encountering this issue, the line in question -
https://github.com/bactopia/bactopia/blob/master/modules/nf-core/mash/dist/main.nf#L111 
...should thereafter look like this(middle line):

```
    declare -a GENUS=(
        "escherichia" "haemophilus" "glaesserella" "klebsiella" "legionella" "mycobacterium" "neisseria" "pseudomonas" "salmonella" "shigella" "staphylococcus" "streptococcus"
    )
```

And of course LisSero will no longer run in Merlin, so you'll have to run that on your own after determining they are present.

**Comment by incoherentian** [comment]
Just adding a note that this still resolves the lissero full-pipeline-crash problem as of a more recent 3.0.2 dev branch.
