### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by yzhzu** [bactopia/bactopia#446]
**Description**
A description of the bug you are experiencing.

**Steps to Reproduce**
```
bactopia ... 3.0.0
bactopia tools ...  bakta or kleborate
!!ERROR!!
```

**Expected Behavior**
A description of what is expected to happen.

**Execution Environment**

- Bactopia Version: [output from `bactopia version`]
- OS: [e.g. Mac, Ubuntu, etc...]
- Environment: [e.g. conda, cluster, container, etc...]

**Additional Information**
Any other information you think might be helpful in squashing this bug.
Core Nextflow options
  runName          : curious_booth
  container        : quay.io/bactopia/bactopia:3.0.0
  launchDir        : /home/shsmu/Data/Temp/Results
  workDir          : /home/shsmu/Data/Temp/Results/work
  projectDir       : /home/shsmu/anaconda3/envs/bactopia/share/bactopia-3.0.0
  userName         : shsmu
  profile          : standard
  configFiles      : /home/shsmu/anaconda3/envs/bactopia/share/bactopia-3.0.0/nextflow.config

Required Parameters
  bactopia         : true

Filtering Parameters
  include          : AT19977.fasta

Optional Parameters
  outdir           : true
  run_name         : bakta

Nextflow Profile Parameters
  condadir         : /home/shsmu/.bactopia/conda
  datasets_cache   : /home/shsmu/.bactopia/datasets
  singularity_cache: /home/shsmu/.bactopia/singularity

Helpful Parameters
  wf               : bakta

!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------
If you use bactopia for your analysis please cite:

* Bactopia
  https://doi.org/10.1128/mSystems.00190-20

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

* Software dependencies
  https://bactopia.github.io/acknowledgements/
--------------------------------------------------------------------
Sep-16 11:14:10.054 [main] WARN  nextflow.Nextflow - 
Sep-16 11:14:10.054 [main] WARN  nextflow.Nextflow - Conda Disclaimer
Sep-16 11:14:10.054 [main] WARN  nextflow.Nextflow - 
Sep-16 11:14:10.055 [main] WARN  nextflow.Nextflow - If you have access to Docker or Singularity, please consider
Sep-16 11:14:10.055 [main] WARN  nextflow.Nextflow - running Bactopia using containers. The containers are less
Sep-16 11:14:10.055 [main] WARN  nextflow.Nextflow - susceptible to Conda environment related issues (e.g. version
Sep-16 11:14:10.055 [main] WARN  nextflow.Nextflow - conflicts) and errors caused by creation of conda environments
Sep-16 11:14:10.056 [main] WARN  nextflow.Nextflow - in parallel (use '--max_cpus 1' to over come this error).
Sep-16 11:14:10.056 [main] WARN  nextflow.Nextflow - 
Sep-16 11:14:10.056 [main] WARN  nextflow.Nextflow - To use containers, you can use the profile parameter
Sep-16 11:14:10.056 [main] WARN  nextflow.Nextflow -     Docker: -profile docker
Sep-16 11:14:10.057 [main] WARN  nextflow.Nextflow -     Singularity: -profile singularity
Sep-16 11:14:10.057 [main] WARN  nextflow.Nextflow - 
Sep-16 11:14:10.057 [main] INFO  nextflow.Nextflow - --------------------------------------------------------------------
Sep-16 11:14:10.076 [main] DEBUG nextflow.Session - Session aborted -- Cause: No signature of method: java.lang.Boolean.startsWith() is applicable for argument types: (String) values: [gs://]
Sep-16 11:14:10.163 [main] ERROR nextflow.cli.Launcher - @unknown
groovy.lang.MissingMethodException: No signature of method: java.lang.Boolean.startsWith() is applicable for argument types: (String) values: [gs://]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at Utils.isLocal(Utils.groovy:83)
        at Utils$isLocal.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at WorkflowBactopiaTools.initialise(WorkflowBactopiaTools.groovy:18)
        at WorkflowBactopiaTools$initialise.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:166)
        at Script_0678c671.runScript(Script_0678c671:20)
        at nextflow.script.BaseScript.run0(BaseScript.groovy:145)
        at nextflow.script.BaseScript.run(BaseScript.groovy:192)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:229)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:215)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:205)
        at nextflow.script.IncludeDef.memoizedMethodPriv$loadModule0PathMapSession(IncludeDef.groovy:151)
        at nextflow.script.IncludeDef.access$0(IncludeDef.groovy)
        at nextflow.script.IncludeDef$__clinit__closure2.doCall(IncludeDef.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
        at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
        at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
        at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
        at nextflow.script.IncludeDef.loadModule0(IncludeDef.groovy)
        at nextflow.script.IncludeDef.load0(IncludeDef.groovy:123)
        at nextflow.script.IncludeDef$load0$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at Script_197bbcbd.runScript(Script_197bbcbd:19)
        at nextflow.script.BaseScript.run0(BaseScript.groovy:145)
        at nextflow.script.BaseScript.run(BaseScript.groovy:192)
        at nextflow.script.ScriptParser.runScript(ScriptParser.groovy:229)
        at nextflow.script.ScriptRunner.run(ScriptRunner.groovy:224)
        at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:130)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:368)
        at nextflow.cli.Launcher.run(Launcher.groovy:494)
        at nextflow.cli.Launcher.main(Launcher.groovy:653)

**Comment by rpetit3** [comment]
Hi @yzhzu 

Is your goal to run Bactopia using Docker or Conda. From the above it's looks like what is happening here is Bactopia is being run in a Docker container, but using Conda for the processing steps.

How would you like run Bactopia? Then we can get it figured out together

Thank you!
Robert

**Comment by yzhzu** [comment]
Dear Robert, 
        thank you very much for your help. actually, we just use bactopia by conda. now we can't deal with the error. can you help us? thank you again.

**Comment by rpetit3** [comment]
Can you by chance share the `.nextflow.log` file that is produced in the directory you executed the command?

**Comment by rpetit3** [comment]
Hi @yzhzu 

I'm going to go ahead and close this issue. If you would like to look at it again, please feel free to reopen it.

Cheers,
Robert
