### ISSUE TITLE
[question] Failed to install bactopia - didn't find info-linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5 component in /.../pkgs/linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5.conda

### ISSUE THREAD

**Issue by siupenyau** [bactopia/bactopia#468]
Hi I am not sure if there was my conda problem. I could not complete the installation of bactopia.
I input the commandline:
mamba create -n bactopia -c bioconda bactopia

I received the following error message:

didn't find info-linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5 component in /home/user/anaconda3/pkgs/linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5.conda

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 361, in _make_single_record
        repodata_record = read_repodata_json(extracted_package_dir)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/gateways/disk/read.py", line 145, in read_repodata_json
        with open(join(extracted_package_directory, "info", "repodata_record.json")) as fi:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/common/compat.py", line 71, in open
        return io_open(
               ^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/home/user/anaconda3/pkgs/linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5/info/repodata_record.json'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 381, in _make_single_record
        raw_json_record = read_index_json(extracted_package_dir)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/gateways/disk/read.py", line 130, in read_index_json
        with open(join(extracted_package_directory, "info", "index.json")) as fi:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/common/compat.py", line 71, in open
        return io_open(
               ^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/home/user/anaconda3/pkgs/linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5/info/index.json'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 945, in exception_converter
        raise e
      File "/home/user/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 938, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 884, in _wrapped_main
        result = do_call(parsed_args, p)
                 ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 760, in do_call
        exit_code = create(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 601, in create
        return install(args, parser, "create")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/mamba/mamba.py", line 568, in install
        handle_txn(conda_transaction, prefix, args, newenv)
      File "/home/user/anaconda3/lib/python3.11/site-packages/mamba/linking.py", line 38, in handle_txn
        unlink_link_transaction.download_and_extract()
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/link.py", line 251, in download_and_extract
        self._pfe.execute()
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 755, in execute
        self.prepare()
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
               ^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 734, in prepare
        self.paired_actions.update(
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 735, in <genexpr>
        (prec, self.make_actions_for_record(prec)) for prec in self.link_precs
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 588, in make_actions_for_record
        extracted_pcrec = next(
                          ^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 589, in <genexpr>
        (
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 592, in <genexpr>
        PackageCacheData(pkgs_dir).query(pref_or_spec)
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 162, in query
        for pcrec in self._package_cache_records.values()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 299, in _package_cache_records
        self.load()
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 123, in load
        package_cache_record = self._make_single_record(base_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 408, in _make_single_record
        extract_tarball(
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/gateways/disk/create.py", line 232, in extract_tarball
        conda_package_handling.api.extract(
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda_package_handling/api.py", line 77, in extract
        format.extract(fn, dest_dir, components=components)
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda_package_handling/conda_fmt.py", line 46, in extract
        _extract(str(fn), str(dest_dir), components=components)
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda_package_handling/streaming.py", line 35, in _extract
        stream = package_streaming.stream_conda_component(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda_package_streaming/package_streaming.py", line 133, in stream_conda_component
        raise LookupError(f"didn't find {component_name} component in {filename}")
    LookupError: didn't find info-linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5 component in /home/user/anaconda3/pkgs/linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5.conda

`$ /home/user/anaconda3/bin/mamba create -n bactopia -c bioconda bactopia`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/user/anaconda3/bin/conda
             CONDA_PREFIX=/home/user/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/user/anaconda3/bin/python
               CONDA_ROOT=/home/user/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                FTP_PROXY=<set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
               LD_PRELOAD=<not set>
                 NO_PROXY=<set>
                     PATH=/home/user/anaconda3/bin:/home/user/anaconda3/condabin:/usr/loca
                          l/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lo
                          cal/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : base
    active env location : /home/user/anaconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /home/user/anaconda3  (writable)
      conda av data dir : /home/user/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/anaconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/anaconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Linux/5.14.0-1034-oem ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

I found that the folder in pkgs/linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5/ was empty. Even I could not update my conda with the same error message. Would anyone please help? Or do I need to reinstall conda? Thank you for help in advance.

With best wishes,

Timothy

**Comment by siupenyau** [comment]
Sorry It should be my conda problem. I will close it here and re-post in appropriate site.
