### ISSUE TITLE
Setup datasets - cgmlst error

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia#49]
```
Traceback (most recent call last):
  File "/home/mdh/mplumb/.conda/envs/bactopia/bin/setup-datasets.py", line 928, in <module>
    ARIBA, PUBMLST, CGMLST = get_available_datasets(args.clear_cache)
  File "/home/mdh/mplumb/.conda/envs/bactopia/bin/setup-datasets.py", line 131, in get_available_datasets
    return [data['ariba'], data['pubmlst'], data['cgmlst']]
KeyError: 'cgmlst'
```

**Comment by rpetit3** [comment]
Removed cgmlst references in `bactopia datasets` https://github.com/bactopia/bactopia/commit/95f3d1aea68ca50d13a6e0eec85777c86e20bdbc
