### ISSUE TITLE
pre-existing bakta_db?[question]

### ISSUE THREAD

**Issue by incoherentian** [bactopia/bactopia#504]
Hello bactopia issues aficionados!
Has anyone had issues like this before?
```
Command exit status:
  1

Command output:

  parse genome sequences...
        imported: 57
        filtered & revised: 57
        contigs: 57

  start annotation...
  predict tRNAs...
        found: 45
  predict tmRNAs...
        found: 1
  predict rRNAs...
        found: 6
  predict ncRNAs...
        found: 27
  predict ncRNA regions...
        found: 7
  predict CRISPR arrays...
        found: 0
  predict & annotate CDSs...
        predicted: 3059
        discarded spurious: 2
        revised translational exceptions: 0
        detected IPSs: 2809
        found PSCs: 204
        found PSCCs: 13
        lookup annotations...
        conduct expert systems...

Command error:
  WARNING: While bind mounting '/gscratch/iboostrom/work/ea/a6878682cedb8014b135ee7acb3c2a:/gscratch/iboostrom/work/ea/a6878682cedb8014b135ee7acb3c2a': destination is already in the mount point list
  Traceback (most recent call last):
    File "/usr/local/bin/bakta", line 10, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.10/site-packages/bakta/main.py", line 275, in main
      expert_amr_found = exp_amr.search(cdss, cds_aa_path)
    File "/usr/local/lib/python3.10/site-packages/bakta/expert/amrfinder.py", line 47, in search
      raise Exception(f"amrfinder error! error code: {proc.returncode}. Please, try 'amrfinder_update --force_update --database {amrfinderplus_db_path}' to update AMRFinderPlus's internal database.")
  Exception: amrfinder error! error code: 1. Please, try 'amrfinder_update --force_update --database /pfs/tc1/project/healthdatasci/bactopia/datasets/bakta_db/db/amrfinderplus-db' to update AMRFinderPlus's internal database.

Work dir:
  /gscratch/iboostrom/work/ea/a6878682cedb8014b135ee7acb3c2a
```

This is when running bactopia with the following:
```
# Export values for bactopia 3.0.2
export NXF_SINGULARITY_CACHEDIR=/project/healthdatasci/bactopia/singularity/
export SBATCH_ACCOUNT="lassoai"


# Set input folder &c.
# Note: remove "/" from end if present
INPUT=/project/lassoai/iboostrom/d026_old_legion_SR

RUN=$(basename ${INPUT})
SAMPLES=$INPUT/${RUN}.fofn
OUTDIR=/project/lassoai/${USER}/bactopia/out_bactopia/${RUN}_${USER}_job${SLURM_JOBID}
mkdir -p $OUTDIR


bactopia\
 -profile arcc\
 --cluster_opts '--account lassoai'\
 --max_cpus 8\
 --datasets_cache /project/healthdatasci/bactopia/datasets/b301_datasets\
 --singularity_cache /project/healthdatasci/bactopia/singularity/\
 --singularity_cache_dir /project/healthdatasci/bactopia/singularity/\
 --samples ${SAMPLES}\
 --outdir $OUTDIR\
 --shovill_assembler spades\
 --use_bakta\
 --bakta_db /project/healthdatasci/bactopia/datasets/bakta_db/db\
 --ask_merlin\
 --max_retry 0\
 --cleanup_workdir
```

I know there are loads of arguments duplicating params in ` -profile arcc`, and duplicated arguments covered by exported values, but now that the rest of the 3.0.2 pipeline's functions are working, I'm afraid to change them!

The bakta_db:
```
[iboostrom@blog1 ~]$ tree /project/healthdatasci/bactopia/datasets/bakta_db/db/amrfinderplus-db/
/project/healthdatasci/bactopia/datasets/bakta_db/db/amrfinderplus-db/
├── 2023-11-15.1
│   ├── AMR.LIB
│   ├── AMR.LIB.h3f
│   ├── AMR.LIB.h3i
│   ├── AMR.LIB.h3m
│   ├── AMR.LIB.h3p
│   ├── AMRProt
│   ├── AMRProt-mutation.tab
│   ├── AMRProt-suppress
│   ├── AMRProt-susceptible.tab
│   ├── AMRProt.pdb
│   ├── AMRProt.phr
│   ├── AMRProt.pin
│   ├── AMRProt.pot
│   ├── AMRProt.psq
│   ├── AMRProt.ptf
│   ├── AMRProt.pto
│   ├── AMR_CDS
│   ├── AMR_CDS.ndb
│   ├── AMR_CDS.nhr
│   ├── AMR_CDS.nin
│   ├── AMR_CDS.not
│   ├── AMR_CDS.nsq
│   ├── AMR_CDS.ntf
│   ├── AMR_CDS.nto
│   ├── database_format_version.txt
│   ├── fam.tab
│   ├── taxgroup.tab
│   └── version.txt
└── latest -> 2023-11-15.1

2 directories, 28 files
```

I downloaded/extracted this database separately. I attempted various ways of getting bakta running with 3.0.1 using a quixotic expedition of bakta main pipeline arguments, bactopia tool bakta arguments, trying to point to previously downloaded bakta_db, even had someone who got bactopia's bakta work work in the past explain their recollection of the process to me and always ran into issues so just stuck with prokka. 

But I'm somewhat desperate for inclusion of updated kegg-compliant annotations from Bakta these days!

Is there a way to force acceptance of the database shown above? Can I request a dude-who-just-can't-get-it-to-work guide to getting [the](https://bactopia.github.io/latest/bactopia/annotator/bakta/#bakta-download) `bakta` `--download_bakta` to work properly, if not?

**Comment by incoherentian** [comment]
I didn't catch the bactopia-dev update via https://github.com/bactopia/bactopia/issues/503 which let me progress with `bactopia -profile arcc --wf bakta --download_bakta --bakta_db /project/healthdatasci/bactopia/datasets/bakta_db --bactopia $OUTDIR --cleanup_workdir`

Thanks for pointing out to me that this was available & relevant @rpetit3 :)

Notes:
-For some reason the `--download_bakta` workflow above required me to specify a `--bactopia` folder to work. I defined an empty folder for the latter.
-When this job had been going for a bit:
```
executor >  slurm (1)
[28/8618f3] process > BACTOPIATOOLS:BAKTA:BAKTA_D... [  0%] 0 of 1
[-        ] process > BACTOPIATOOLS:BAKTA:BAKTA_RUN  -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSO... -
```
```
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
          15018538 beartooth nf-BACTO iboostro  R      36:53      1 b522
          15018537     moran bactopia iboostro  R      37:38      1 m276
```
...with no data appearing to have downloaded in the target db directory:
```
[iboostrom@blog2 iboostrom]$ ll /project/healthdatasci/bactopia/datasets/bakta_db
total 0
```
I had some concern the download was not working, and didn't know how to check nodes' bandwidth usage in SLURM. To assuage any concerns similar to mine about this, the download function was legitimately working (and just downloading to an intermediate temp dir in the work directory).
```
[iboostrom@blog2 iboostrom]$ ll -tr work/28/8618f3351e92011b2ddc8c69b49116/bakta/
total 38478081
-rw-rw-r-- 1 iboostrom iboostrom 39401553410 Apr  9 10:22 db.tar.gz
drwx--S--- 3 iboostrom iboostrom        4096 Apr  9 10:30 db
```
And moved appropriately once finished: 
```
[iboostrom@blog2 iboostrom]$ ls /project/healthdatasci/bactopia/datasets/bakta_db
bakta-full  versions.yml
```
This just finished so I'll update and close this once I've tested it within the main pipeline. Thanks as always @rpetit3!

**Comment by incoherentian** [comment]
Only issue is that I specified `--download_bakta --bakta_db /project/healthdatasci/bactopia/datasets/bakta_db/` but had to change this to `--bakta_db /project/healthdatasci/bactopia/datasets/bakta_db/bakta-full/db` for bactopia to later recognize the downloaded db. With that, working perfectly now!

Thanks again again :)
