### ISSUE TITLE
CheckM failed

### ISSUE THREAD

**Issue by riccabolla** [bactopia/bactopia#541]
Hi,
I am trying to use checkM, however it fails. The following is the command.log:
[2024-09-04 12:39:57] INFO: CheckM v1.2.2
[2024-09-04 12:39:57] INFO: checkm lineage_wf ./ results/ --tab_table --threads 12 --pplacer_threads 12 --alignment_file results/SRR30401990-genes.aln --file results/SRR30401990-results.txt --reduced_tree --unique 10 --multi 10 --aai_strain 0.9 --length 0.7
[2024-09-04 12:39:57] INFO: CheckM data: /home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/checkm_data
[2024-09-04 12:39:57] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2024-09-04 12:39:57] INFO: Identifying marker genes in 1 bins with 12 threads:
    Finished processing 0 of 1 (0.00%) bins.
    Finished processing 1 of 1 (100.00%) bins.
[2024-09-04 12:40:09] INFO: Saving HMM info to file.
[2024-09-04 12:40:09] INFO: Calculating genome statistics for 1 bins with 12 threads:
    Finished processing 0 of 1 (0.00%) bins.
    Finished processing 1 of 1 (100.00%) bins.
[2024-09-04 12:40:10] INFO: Extracting marker genes to align.
[2024-09-04 12:40:10] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
[2024-09-04 12:40:10] INFO: Extracting 43 HMMs with 12 threads:
    Finished extracting 0 of 43 (0.00%) HMMs.
    Finished extracting 1 of 43 (2.33%) HMMs.
    Finished extracting 2 of 43 (4.65%) HMMs.
    Finished extracting 3 of 43 (6.98%) HMMs.
    Finished extracting 4 of 43 (9.30%) HMMs.
    Finished extracting 5 of 43 (11.63%) HMMs.
    Finished extracting 6 of 43 (13.95%) HMMs.
    Finished extracting 7 of 43 (16.28%) HMMs.
    Finished extracting 8 of 43 (18.60%) HMMs.
    Finished extracting 9 of 43 (20.93%) HMMs.
    Finished extracting 10 of 43 (23.26%) HMMs.
    Finished extracting 11 of 43 (25.58%) HMMs.
    Finished extracting 12 of 43 (27.91%) HMMs.
    Finished extracting 13 of 43 (30.23%) HMMs.
    Finished extracting 14 of 43 (32.56%) HMMs.
    Finished extracting 15 of 43 (34.88%) HMMs.
    Finished extracting 16 of 43 (37.21%) HMMs.
    Finished extracting 17 of 43 (39.53%) HMMs.
    Finished extracting 18 of 43 (41.86%) HMMs.
    Finished extracting 19 of 43 (44.19%) HMMs.
    Finished extracting 20 of 43 (46.51%) HMMs.
    Finished extracting 21 of 43 (48.84%) HMMs.
    Finished extracting 22 of 43 (51.16%) HMMs.
    Finished extracting 23 of 43 (53.49%) HMMs.
    Finished extracting 24 of 43 (55.81%) HMMs.
    Finished extracting 25 of 43 (58.14%) HMMs.
    Finished extracting 26 of 43 (60.47%) HMMs.
    Finished extracting 27 of 43 (62.79%) HMMs.
    Finished extracting 28 of 43 (65.12%) HMMs.
    Finished extracting 29 of 43 (67.44%) HMMs.
    Finished extracting 30 of 43 (69.77%) HMMs.
    Finished extracting 31 of 43 (72.09%) HMMs.
    Finished extracting 32 of 43 (74.42%) HMMs.
    Finished extracting 33 of 43 (76.74%) HMMs.
    Finished extracting 34 of 43 (79.07%) HMMs.
    Finished extracting 35 of 43 (81.40%) HMMs.
    Finished extracting 36 of 43 (83.72%) HMMs.
    Finished extracting 37 of 43 (86.05%) HMMs.
    Finished extracting 38 of 43 (88.37%) HMMs.
    Finished extracting 39 of 43 (90.70%) HMMs.
    Finished extracting 40 of 43 (93.02%) HMMs.
    Finished extracting 41 of 43 (95.35%) HMMs.
    Finished extracting 42 of 43 (97.67%) HMMs.
    Finished extracting 43 of 43 (100.00%) HMMs.
[2024-09-04 12:40:10] INFO: Aligning 43 marker genes with 12 threads:
    Finished aligning 0 of 43 (0.00%) marker genes.
    Finished aligning 1 of 43 (2.33%) marker genes.
    Finished aligning 2 of 43 (4.65%) marker genes.
    Finished aligning 3 of 43 (6.98%) marker genes.
    Finished aligning 4 of 43 (9.30%) marker genes.
    Finished aligning 5 of 43 (11.63%) marker genes.
    Finished aligning 6 of 43 (13.95%) marker genes.
    Finished aligning 7 of 43 (16.28%) marker genes.
    Finished aligning 8 of 43 (18.60%) marker genes.
    Finished aligning 9 of 43 (20.93%) marker genes.
    Finished aligning 10 of 43 (23.26%) marker genes.
    Finished aligning 11 of 43 (25.58%) marker genes.
    Finished aligning 12 of 43 (27.91%) marker genes.
    Finished aligning 13 of 43 (30.23%) marker genes.
    Finished aligning 14 of 43 (32.56%) marker genes.
    Finished aligning 15 of 43 (34.88%) marker genes.
    Finished aligning 16 of 43 (37.21%) marker genes.
    Finished aligning 17 of 43 (39.53%) marker genes.
    Finished aligning 18 of 43 (41.86%) marker genes.
    Finished aligning 19 of 43 (44.19%) marker genes.
    Finished aligning 20 of 43 (46.51%) marker genes.
    Finished aligning 21 of 43 (48.84%) marker genes.
    Finished aligning 22 of 43 (51.16%) marker genes.
    Finished aligning 23 of 43 (53.49%) marker genes.
    Finished aligning 24 of 43 (55.81%) marker genes.
    Finished aligning 25 of 43 (58.14%) marker genes.
    Finished aligning 26 of 43 (60.47%) marker genes.
    Finished aligning 27 of 43 (62.79%) marker genes.
    Finished aligning 28 of 43 (65.12%) marker genes.
    Finished aligning 29 of 43 (67.44%) marker genes.
    Finished aligning 30 of 43 (69.77%) marker genes.
    Finished aligning 31 of 43 (72.09%) marker genes.
    Finished aligning 32 of 43 (74.42%) marker genes.
    Finished aligning 33 of 43 (76.74%) marker genes.
    Finished aligning 34 of 43 (79.07%) marker genes.
    Finished aligning 35 of 43 (81.40%) marker genes.
    Finished aligning 36 of 43 (83.72%) marker genes.
    Finished aligning 37 of 43 (86.05%) marker genes.
    Finished aligning 38 of 43 (88.37%) marker genes.
    Finished aligning 39 of 43 (90.70%) marker genes.
    Finished aligning 40 of 43 (93.02%) marker genes.
    Finished aligning 41 of 43 (95.35%) marker genes.
    Finished aligning 42 of 43 (97.67%) marker genes.
    Finished aligning 43 of 43 (100.00%) marker genes.
[2024-09-04 12:40:10] INFO: Reading marker alignment files.
[2024-09-04 12:40:10] INFO: Concatenating alignments.
[2024-09-04 12:40:10] INFO: Placing 1 bins into the genome tree with pplacer (be patient).
[2024-09-04 12:41:42] INFO: { Current stage: 0:01:45.802 || Total: 0:01:45.802 }
[2024-09-04 12:41:42] INFO: [CheckM - lineage_set] Inferring lineage-specific marker sets.
[2024-09-04 12:41:42] INFO: Reading HMM info from file.

Unexpected error: <class 'ValueError'>
Traceback (most recent call last):
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/lib/python3.12/site-packages/checkm/main.py", line 980, in parseOptions
    self.lineageSet(options)
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/lib/python3.12/site-packages/checkm/main.py", line 249, in lineageSet
    resultsParser.analyseResults(options.tree_dir,
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/lib/python3.12/site-packages/checkm/resultsParser.py", line 63, in analyseResults
    binStats = self.parseBinStats(outDir, binStatsFile)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/lib/python3.12/site-packages/checkm/resultsParser.py", line 155, in parseBinStats
    binStats[lineSplit[0]] = ast.literal_eval(lineSplit[1])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/lib/python3.12/ast.py", line 112, in literal_eval
    return _convert(node_or_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/lib/python3.12/ast.py", line 101, in _convert
    return dict(zip(map(_convert, node.keys),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/lib/python3.12/ast.py", line 111, in _convert
    return _convert_signed_num(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/lib/python3.12/ast.py", line 85, in _convert_signed_num
    return _convert_num(node)
           ^^^^^^^^^^^^^^^^^^
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/lib/python3.12/ast.py", line 76, in _convert_num
    _raise_malformed_node(node)
  File "/home/cento/rbollini/.bactopia/conda/bioconda--checkm-genome-1.2.2/lib/python3.12/ast.py", line 73, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string on line 1: <ast.Call object at 0x7f579da0ffd0>

Does anyone know why and/or what should i do to overcome this issue?

Thanks

Riccardo

**Comment by rpetit3** [comment]
Hi @riccabolla 

This looks related to https://github.com/Ecogenomics/CheckM/issues/400 I will get this fixed in the next version of Bactopia.

**Comment by rpetit3** [comment]
Should be fixed in https://github.com/bactopia/bactopia/commit/c5e970eb4b22cef61d5040bb35d7bcf2abfda610

Will be available in next release

**Comment by rpetit3** [comment]
Hi @riccabolla 

This should now be fixed in https://github.com/bactopia/bactopia/releases/tag/v3.1.0 

Please let me know if you still have this issue

Cheers,
Robert
