### ISSUE TITLE
[bug] `slurm` profile incompatible with version 3.1.0

### ISSUE THREAD

**Issue by victorlin** [bactopia/bactopia#558]
**Description**

Running with the [`slurm` profile](https://github.com/bactopia/bactopia/blob/474be2d4d0694c392436e4bda17d0b1e6814389b/conf/profiles/slurm.config) shows an error

```
ERROR ~ No such variable: m
```

**Steps to Reproduce**

1. Install Bactopia 3.1.0 via conda
2. Run `bactopia -profile test,slurm`

Output:

```
2024-09-27 15:43:21 INFO     2024-09-27 15:43:21:root:INFO - Checking if environment pre-builds are needed (this may take a while if building for the first time)                                                                            download.py:544

 N E X T F L O W   ~  version 24.04.4

ERROR ~ No such variable: m

 -- Check '.nextflow.log' file for details
```

<details>
<summary>
contents of .nextflow.log
</summary>

```
Sep-27 15:43:27.174 [main] DEBUG nextflow.cli.Launcher - $> nextflow run /home/vlin/miniconda3/envs/bactopia310//share/bactopia-3.1.0/main.nf -w /home/vlin/work/ -profile test,slurm
Sep-27 15:43:27.308 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.04.4
Sep-27 15:43:27.347 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/vlin/.nextflow/plugins; core-plugins: nf-amazon@2.5.3,nf-azure@1.6.1,nf-cloudcache@0.4.1,nf-codecommit@0.2.1,nf-console@1.1.3,nf-ga4gh@1.3.0,nf-google@1.13.2-patch1,nf-tower@1.9.1,nf-wave@1.4.2-patch1
Sep-27 15:43:27.376 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Sep-27 15:43:27.378 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Sep-27 15:43:27.383 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.12.0 in 'deployment' mode
Sep-27 15:43:27.404 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Sep-27 15:43:27.464 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/vlin/miniconda3/envs/bactopia310/share/bactopia-3.1.0/nextflow.config
Sep-27 15:43:27.472 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/vlin/miniconda3/envs/bactopia310/share/bactopia-3.1.0/nextflow.config
Sep-27 15:43:27.543 [main] DEBUG n.secret.LocalSecretsProvider - Secrets store: /home/vlin/.nextflow/secrets/store.json
Sep-27 15:43:27.550 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@411291e5] - activable => nextflow.secret.LocalSecretsProvider@411291e5
Sep-27 15:43:27.562 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `test,slurm`
Sep-27 15:43:31.375 [main] ERROR nextflow.cli.Launcher - Unable to parse config file: '/home/vlin/miniconda3/envs/bactopia310/share/bactopia-3.1.0/nextflow.config'

  No such property: m for class: nextflow.util.Duration
  Possible solutions: log

groovy.lang.MissingPropertyException: No such property: m for class: nextflow.util.Duration
Possible solutions: log
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:67)
	at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:163)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at ScriptF061A7000688DE7BDFBCF5762F7FEDE3$_run_closure2.doCall(ScriptF061A7000688DE7BDFBCF5762F7FEDE3:15)
	at ScriptF061A7000688DE7BDFBCF5762F7FEDE3$_run_closure2.doCall(ScriptF061A7000688DE7BDFBCF5762F7FEDE3)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:436)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1140)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:165)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:165)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:355)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBase$_includeConfig_closure2.doCall(ConfigBase.groovy:124)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1140)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:165)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:355)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBase$_includeConfig_closure2.doCall(ConfigBase.groovy:124)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1140)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at ScriptF061A7000688DE7BDFBCF5762F7FEDE3.run(ScriptF061A7000688DE7BDFBCF5762F7FEDE3:11)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1333)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1088)
	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1017)
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1088)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.Closure.call(Closure.java:433)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:355)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBase.includeConfig(ConfigBase.groovy:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:342)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:645)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:391)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:328)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at ScriptCB0C62B99996983ABE42ADDAA4079C7F$_run_closure1$_closure10.doCall(ScriptCB0C62B99996983ABE42ADDAA4079C7F:56)
	at ScriptCB0C62B99996983ABE42ADDAA4079C7F$_run_closure1$_closure10.doCall(ScriptCB0C62B99996983ABE42ADDAA4079C7F)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:402)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1140)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:165)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:165)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBase$_includeConfig_closure2.doCall(ConfigBase.groovy:124)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1140)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:645)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:628)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeOnDelegationObjects(ClosureMetaClass.java:391)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:328)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at ScriptCB0C62B99996983ABE42ADDAA4079C7F$_run_closure1.doCall(ScriptCB0C62B99996983ABE42ADDAA4079C7F:52)
	at ScriptCB0C62B99996983ABE42ADDAA4079C7F$_run_closure1.doCall(ScriptCB0C62B99996983ABE42ADDAA4079C7F)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:378)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1140)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:165)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:165)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:355)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBase$_includeConfig_closure2.doCall(ConfigBase.groovy:124)
	at jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1140)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at ScriptCB0C62B99996983ABE42ADDAA4079C7F.run(ScriptCB0C62B99996983ABE42ADDAA4079C7F:1)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1333)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1088)
	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1017)
	at groovy.lang.MetaClassImpl.doInvokeMethod(MetaClassImpl.java:1207)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1088)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.Closure.call(Closure.java:433)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:355)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBase.includeConfig(ConfigBase.groovy:125)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.selectMethod(IndyInterface.java:355)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:457)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1140)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:165)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at _nf_config_f16fe971.run(_nf_config_f16fe971:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigParser$_parse_closure5.doCall(ConfigParser.groovy:457)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaMethod.invoke(ClosureMetaMethod.java:88)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1140)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:165)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:486)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigParser.parse(ConfigParser.groovy:312)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.parse0(ConfigBuilder.groovy:439)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.merge0(ConfigBuilder.groovy:425)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:375)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:320)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:814)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:827)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:328)
	at nextflow.cli.Launcher.run(Launcher.groovy:503)
	at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

</details>

**Expected Behavior**

No error

**Execution Environment**

- Bactopia Version: 3.1.0
- OS: Ubuntu 18.04.6 LTS
- Environment: [cluster](https://sciwiki.fredhutch.org/scicomputing/compute_overview/)

**Additional Information**

I found 2 workarounds:

1. Remove `process.time` https://github.com/bactopia/bactopia/blob/474be2d4d0694c392436e4bda17d0b1e6814389b/conf/profiles/slurm.config#L15
2. Set `params.max_time`

Maybe due to b3998beed78be643624c99ed1e46df2bf84c7e02, summarized in changelog as

https://github.com/bactopia/bactopia/blob/474be2d4d0694c392436e4bda17d0b1e6814389b/CHANGELOG.md?plain=1#L27

**Comment by rpetit3** [comment]
Hi @victorlin 

Thank you for reporting this, totally forget about them. I've fixed it in https://github.com/bactopia/bactopia/commit/0af963f78b6e7376b2e8fa7feb870b0f6ed687b2

If you want to use it now, you can use my dev build.

```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
```

If you give a try, let me know if it still causes issues,
Robert

**Comment by victorlin** [comment]
Thanks for the quick response! I just tested and am getting a new error:

```
│ /home/vlin/miniconda3/envs/bactopia-dev/lib/python3.11/site-packages/bactopia/cli/download.py:107 in parse_workflows                                                                                 │
│                                                                                                                                                                                                      │
│   106 │   available_workflows = []                                                                                                                                                                   │
│ ❱ 107 │   nf_config, stderr = execute(                                                                                                                                                               │
│   108 │   │   f"nextflow config -flat {bactopia_path}/main.nf", capture=True                                                                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: cannot unpack non-iterable NoneType object

 N E X T F L O W   ~  version 24.04.4

Cannot find script file: /home/vlin/miniconda3/envs/bactopia-dev//share/bactopia-3.1.0/main.nf
```

<details>
<summary>Full output</summary>

```
$ bactopia -profile test,slurm
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮          
│ /home/vlin/miniconda3/envs/bactopia-dev/bin/bactopia-download:10 in <module>                                                                                                                         │          
│                                                                                                                                                                                                      │          
│    9 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                                                                                                                            │          
│ ❱ 10 │   sys.exit(main())                                                                                                                                                                            │          
│   11                                                                                                                                                                                                 │          
│                                                                                                                                                                                                      │          
│ /home/vlin/miniconda3/envs/bactopia-dev/lib/python3.11/site-packages/bactopia/cli/download.py:569 in main                                                                                            │
│                                                                                                                                                                                                      │
│   568 │   else:                                                                                                                                                                                      │
│ ❱ 569 │   │   download()                                                                                                                                                                             │
│   570                                                                                                                                                                                                │
│                                                                                                                                                                                                      │
│ /home/vlin/miniconda3/envs/bactopia-dev/lib/python3.11/site-packages/click/core.py:1157 in __call__                                                                                                  │
│                                                                                                                                                                                                      │
│   1156 │   │   """Alias for :meth:`main`."""                                                                                                                                                         │
│ ❱ 1157 │   │   return self.main(*args, **kwargs)                                                                                                                                                     │
│   1158                                                                                                                                                                                               │
│                                                                                                                                                                                                      │
│ /home/vlin/miniconda3/envs/bactopia-dev/lib/python3.11/site-packages/rich_click/rich_command.py:152 in main                                                                                          │
│                                                                                                                                                                                                      │
│   151 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                                                                                                                       │
│ ❱ 152 │   │   │   │   │   rv = self.invoke(ctx)                                                                                                                                                      │
│   153 │   │   │   │   │   if not standalone_mode:                                                                                                                                                    │
│                                                                                                                                                                                                      │
│ /home/vlin/miniconda3/envs/bactopia-dev/lib/python3.11/site-packages/click/core.py:1434 in invoke                                                                                                    │
│                                                                                                                                                                                                      │
│   1433 │   │   if self.callback is not None:                                                                                                                                                         │
│ ❱ 1434 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                                                                                                                    │
│   1435                                                                                                                                                                                               │
│                                                                                                                                                                                                      │
│ /home/vlin/miniconda3/envs/bactopia-dev/lib/python3.11/site-packages/click/core.py:783 in invoke                                                                                                     │
│                                                                                                                                                                                                      │
│    782 │   │   │   with ctx:                                                                                                                                                                         │
│ ❱  783 │   │   │   │   return __callback(*args, **kwargs)                                                                                                                                            │
│    784                                                                                                                                                                                               │
│                                                                                                                                                                                                      │
│ /home/vlin/miniconda3/envs/bactopia-dev/lib/python3.11/site-packages/bactopia/cli/download.py:535 in download                                                                                        │
│                                                                                                                                                                                                      │
│   534 │   include_merlin = True if "--ask_merlin" in unknown else False                                                                                                                              │
│ ❱ 535 │   workflow_modules = parse_workflows(                                                                                                                                                        │
│   536 │   │   bactopia_path, include_merlin=include_merlin, build_all=build_all                                                                                                                      │
│                                                                                                                                                                                                      │
│ /home/vlin/miniconda3/envs/bactopia-dev/lib/python3.11/site-packages/bactopia/cli/download.py:107 in parse_workflows                                                                                 │
│                                                                                                                                                                                                      │
│   106 │   available_workflows = []                                                                                                                                                                   │
│ ❱ 107 │   nf_config, stderr = execute(                                                                                                                                                               │
│   108 │   │   f"nextflow config -flat {bactopia_path}/main.nf", capture=True                                                                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: cannot unpack non-iterable NoneType object

 N E X T F L O W   ~  version 24.04.4

Cannot find script file: /home/vlin/miniconda3/envs/bactopia-dev//share/bactopia-3.1.0/main.nf
```

</details>

**Comment by rpetit3** [comment]
Hi @victorlin 

do you mind retrying a dev build? I goofed on updating the version (just fixed it), which caused you issue (haha now here's to hoping the latest changes I made today didn't break anything! haven't tested yet)

```
mamba create -n bactopia-dev -c rpetit3 -c conda-forge -c bioconda bactopia
```

**Comment by victorlin** [comment]
Thanks, it gets past this step now! I'm running into some other issues so I can't verify that `-profile test` works fully yet, but I'll open another issue.
